src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Homepage__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Allow pledge (action) to be shown on the homepage.</inlineHelpText>
        <label>Homepage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Leave this box ticked if you are happy for your pledge to be displayed on our website.</inlineHelpText>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEBRecentNewsTest.cls
@isTest(seeAllData=false)
public with sharing class WEBRecentNewsTest {
	static testMethod void recentNewsTest() {
		Action__c action = new Action__c();
		action.Homepage__c = TRUE;
		action.Public__c = TRUE;
		action.Action__c = '*** TEST ACTION ***';

        insert action;

        WEBRecentActions controller;

        Test.startTest();
        controller = new WEBRecentActions();

        system.assertEquals(1, controller.actions.size());
        Test.stoptest();
	}
}