src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Verefied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User Code Verefied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Friends_Influenced__c</fullName>
        <label>Number of Friends Influenced</label>
        <summarizedField>DF_Event__c.Number_of_Attendees__c</summarizedField>
        <summaryForeignKey>DF_Event__c.Session_Organiser__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospective</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hiatus/Resting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_Of_Attendee_Records__c</fullName>
        <label>Number Of Attendee Records</label>
        <summaryFilterItems>
            <field>DF_EventAttendee__c.Event_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>DF_EventAttendee__c.DF_Event__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <label>Number of Attendees</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Number of Places</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Champion_Training_Course</fullName>
        <active>true</active>
        <description>Events organised by Alzheimers Society/Trusted Partners</description>
        <label>Champion Training Course</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Attendee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEBChampion.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX controller class for VF Page WEBChampion.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex Class that looks after the WEBChampion VF Page.
 *					This class determins what to render for the Champion on the Champion Dashboard
 * 					based on different flags etc.
 *               
 *  Modification History
 *  Date            Who         Description 
 *  27/05/2014		CSL			New code to enable 'You have sessions to be reported on' prompt                  
*******************************************************************************************/
public with sharing class WEBChampion extends WEBController {
	public final String CHAMPION_CODE = 'Register Champions\' code';
	public final String CHAMPION_CODE_ENTERED = 'Registered Champions\' code';
	public final String INVALID_CHAMPION_CODE = 'The Champions\' code you entered was not recognised. Please try again.';
	public final String ALERT_ERROR_CLASS = 'alert-error';
	public final String STATUS_CANCELLED = 'Cancelled';
	public final String RT_CHAMPION_COURSE = 'Champion_Training_Course';

	public User thisUser {
		get {
			return WEBController.thisUser;
		}
		set;
	}

	public List<DF_Event__c> upcomingEvents {
		get {
			if (upcomingEvents == null){
				upcomingEvents = new List<DF_Event__c>();
			}
			return upcomingEvents;
		}
		set;
	}
	
	public List<DF_Event__c> eventsRequiringFeedback {
		get {
			if (eventsRequiringFeedback == null){
				eventsRequiringFeedback = new List<DF_Event__c>();
			}
			return eventsRequiringFeedback;
		}
		set;
	}

	public Boolean isChampion {get;set;}
	public Boolean isChampionConverted {get; set;}
	public Boolean registeredAsChampion {get;set;}
	public Boolean newChampionRegistration {get; set;}
	public Boolean showReportingPrompt {get; set;}

	public String championCode {get;set;}
	public String championCodeError {get;set;}
	public String championCodeText {get;set;}

	public String messageArea {get;set;}
	public String messageAreaClass {get;set;}

	public Integer sessionCount {get;set;}
	public Integer friendCount {get;set;}
	public Integer friendActionCount {get;set;}
	public boolean isTraining {get; set;}
	public boolean isSession {get; set;}
	public boolean showViewDetailsButton {get; set;}
	public boolean showSaveConfirmation {get; set;}
	
	public Map<Id, RecordType> rtMap {get; set;}
	public Map<String, RecordType> rtMapByName {get; set;}
	
	public List<DF_EventAttendee__c> myTraining {get; set;}
	
	public DF_Contact__c contact {get; set;}
	
	public Page_Snippet__c totalFriendsSnippet {
		get {
			if (totalFriendsSnippet == null){
				totalFriendsSnippet = [select p.Body_Text__c, p.Unique_Name__c from Page_Snippet__c p where p.Unique_Name__c = 'DementiaFriendsTotalSnippet' LIMIT 1];
			}
			return totalFriendsSnippet;
		}
		set ;
	}

	public PageReference registerCode() {
		messageArea = null;
		messageAreaClass = null;
		championCodeError = '';
		if (championCode.length() == 0) {
			messageArea = INVALID_CHAMPION_CODE;
			messageAreaClass = ALERT_ERROR_CLASS;
		}else{
			system.debug('*** -- Registering code ' + championCode + ' -- ***');
			registeredAsChampion = WEBConversionClass.convertFriendToChampion(thisUser.ContactId, championCode);
			
			List<DF_Contact__c> contacts = [SELECT Id, Number_of_Friends_Influenced__c, Code_Verefied__c, Status__c FROM DF_Contact__c WHERE Portal_Contact__r.Id = :WEBController.thisUser.ContactId LIMIT 1];
			contact = null;

			if (!contacts.isEmpty()){
				contact = contacts[0];
			}
			
			isChampion = WEBConversionClass.isChampion(thisUser.contactId);
			isChampionConverted = WEBConversionClass.isChampionConverted(thisUser.contactId);
			if (!contact.Code_Verefied__c){
				messageArea = INVALID_CHAMPION_CODE;
				messageAreaClass = ALERT_ERROR_CLASS;
			}
			
		}
		return null;
	}

	public PageReference convertBackToFriend() {
		system.debug('*** -- Into convertBackToFriend -- ***');
		Boolean isSuccess = WEBConversionClass.convertChampionToFriend(thisUser.contactId, WEBGlobalSettings.friendConvertCode);
		system.debug('*** -- Conversion returned : ' + isSuccess + ' -- ***');

		if (isSuccess) {
			PageReference pr = Page.WEBFriend;
			pr.getParameters().put('convertBack', 'TRUE');
			return pr;
		}
		else
			return null;
	}

	public WEBChampion() {
		system.debug('*** -- Into WEBChampion Constructor -- ***');
		sessionCount = 0;
		friendCount = 0;
		friendActionCount = 0;
		registeredAsChampion = FALSE;
		newChampionRegistration = false;
		isSession = false;
		isTraining = false;
		showReportingPrompt = false;
		if (ApexPages.currentPage().getParameters().get('nr') != null){
			newChampionRegistration = true;	
		}
		
		if (ApexPages.currentPage().getParameters().get('ds') != null){
			showSaveConfirmation = true;
		}else {
			showSaveConfirmation = false;
		}

		rtMapByName = new Map<String, RecordType>();
		rtMap = new Map<Id, RecordType>();
		for (RecordType r : [select r.Id, r.DeveloperName from RecordType r where r.SobjectType = 'DF_Event__c' and r.IsActive = true]){
			rtMap.put(r.Id, r);
			rtMapByName.put(r.DeveloperName, r);
		}

		List<DF_Contact__c> contacts = [SELECT Id, Number_of_Friends_Influenced__c, Code_Verefied__c, Status__c FROM DF_Contact__c WHERE Portal_Contact__r.Id = :WEBController.thisUser.ContactId LIMIT 1];

		contact = null;

		if (!contacts.isEmpty())
			contact = contacts[0];

		if (contact != null) {
			friendCount = contact.Number_of_Friends_Influenced__c.intValue();
		}

		upcomingEvents = new List<DF_Event__c>();
		
		for (DF_Event__c dfe : [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c, Number_of_Attendee_Records__c FROM DF_Event__c WHERE Session_Organiser__c = :contact.Id AND Event_Date_Time__c >= TODAY and Event_Status__c != :STATUS_CANCELLED LIMIT 20]){
			if (dfe.Event_Date_Time__c.getTime() > system.now().getTime()){
				upcomingEvents.add(dfe);
			}
		}

		//upcomingEvents = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c, Number_of_Attendee_Records__c FROM DF_Event__c WHERE Session_Organiser__c = :contact.Id AND Event_Date_Time__c >= TODAY and Event_Status__c != :STATUS_CANCELLED LIMIT 20];
		
		eventsRequiringFeedback = new List<DF_Event__c>();
		for (DF_Event__c dfe : [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c FROM DF_Event__c WHERE Session_Organiser__c = :contact.Id AND Event_Date_Time__c <= TODAY AND (Number_of_Attendees__c = null OR Number_of_Attendees__c = 0) and Event_Status__c != :STATUS_CANCELLED LIMIT 10]){
			
			if (dfe.Event_Date_Time__c.getTime() < system.now().getTime()){
				eventsRequiringFeedback.add(dfe);
			}
		}
		
		//eventsRequiringFeedback = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c FROM DF_Event__c WHERE Session_Organiser__c = :contact.Id AND Event_Date_Time__c < TODAY AND (Number_of_Attendees__c = null OR Number_of_Attendees__c = 0) and Event_Status__c != :STATUS_CANCELLED LIMIT 10];
		if (eventsRequiringFeedback.size() > 0){
			showReportingPrompt = true;
		}

		List<DF_Event__c> events = [SELECT Id FROM DF_Event__c WHERE Session_Organiser__r.Portal_Contact__r.Id = :WEBController.thisUser.ContactId LIMIT 1000];

		if (events != null && !events.isEmpty())
			sessionCount = events.size();

		isChampion = WEBConversionClass.isChampion(thisUser.contactId);
		isChampionConverted = WEBConversionClass.isChampionConverted(thisUser.contactId);
		system.debug('*** -- WEBChampion isChampion = ' + isChampion + ' -- ***');
		system.debug('*** -- WEBChampion isChampionConverted = ' + isChampionConverted + ' -- ***');
		myTraining = new List<DF_EventAttendee__c>();
		if (isChampionConverted){
				championCodeText = CHAMPION_CODE_ENTERED;
		}else {
				RecordType championRT = rtMapByName.get(RT_CHAMPION_COURSE);
				championCodeText = CHAMPION_CODE;
				myTraining = [SELECT Id, DF_Event__r.Event_Date_Time__c, DF_Event__r.City__c, DF_Event__r.Postcode__c, DF_Event__r.Number_of_Attendees__c, DF_Event__r.RecordTypeId 
							FROM DF_EventAttendee__C WHERE DF_Contact__r.Portal_Contact__c = :thisUser.ContactId
							and DF_Event__r.RecordTypeId = :championRT.Id LIMIT 1];
				if (!myTraining.isEmpty()){
					isTraining = true;
					isSession = false;
					showViewDetailsButton = true;
				}
		}

		system.debug('*** -- WEBChampion Champion Code Text ' + championCodeText + ' -- ***');

		List<DF_EventAttendee__c> myEventContacts = [SELECT DF_Contact__r.Id FROM DF_EventAttendee__c WHERE DF_Event__c = :events LIMIT 1000];

		List<Id> myEventContactsId = new List<Id>();
		
		if (myEventContacts != null && !myEventContacts.isEmpty()) {
		
			for (DF_EventAttendee__c att : myEventContacts) {
				myEventContactsId.add(att.DF_Contact__r.Id);
			}

			List<Action__c> myEventContactsActions = [SELECT Id FROM Action__c WHERE DF_Contact__r.Id = :myEventContactsId LIMIT 1000];
	
			if (myEventContactsActions != null && !myEventContactsActions.isEmpty())
				friendActionCount = myEventContactsActions.size();
		}
	}
}