src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Homepage__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Allow pledge (action) to be shown on the homepage.</inlineHelpText>
        <label>Homepage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Leave this box ticked if you are happy for your pledge to be displayed on our website.</inlineHelpText>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEBRecentActions.cls
public with sharing class WEBRecentActions {
	public List<Action__c> actions {
		get {
			if (actions == null)
				actions = new List<Action__c>();
			return actions;
		}
		private set;
	}

	public WEBRecentActions() {
		actions = [SELECT DF_Contact__r.Name, DF_Contact__r.Id, Id, Action__c, Public__c, Homepage__c FROM Action__c WHERE Public__c = TRUE AND Homepage__c = TRUE ORDER BY CreatedDate DESC LIMIT 10];
		system.debug('*** -- got Actions -- ***');
		
	}
}