src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEBFriendCreateActionTest.cls
@IsTest global with sharing  class WEBFriendCreateActionTest {
	@IsTest(SeeAllData=false) global static void createActionTest() {
		DF_Contact__c c = new DF_Contact__c();
		c.Portal_Contact__c = WEBController.thisUser.ContactId;
		c.First_Name__c = '*** TEST ***';
		c.Last_Name__c = '*** TEST ***';
		c.Email__c = 'test.test@myemail.com';
		insert c;

		WEBFriendCreateAction controller = new WEBFriendCreateAction ();

        System.assertNotEquals(controller, null);

        controller.publicCheckbox = TRUE;
		controller.action = '***';

		System.assertNotEquals(null, controller.cancel());
		System.assertNotEquals(null, controller.save());
	}
	
	@IsTest(SeeAllData=false) global static void createActionTestWithAction() {
		DF_Contact__c c = new DF_Contact__c();
		c.Portal_Contact__c = WEBController.thisUser.ContactId;
		c.First_Name__c = '*** TEST ***';
		c.Last_Name__c = '*** TEST ***';
		c.Email__c = 'test.test@myemail.com';
		insert c;
		
		Action__c act = new Action__c();
		act.DF_Contact__c = c.Id;
		act.Action__c = '*** TEST ***';
		insert act;
		
		
		PageReference pr = Page.WEBFriendCreateAction;
		pr.getParameters().put('Id',act.Id);
		test.setCurrentPage(pr);
		
		WEBFriendCreateAction controller = new WEBFriendCreateAction ();

        System.assertNotEquals(controller, null);

        controller.publicCheckbox = TRUE;
		controller.action = '***';

		System.assertNotEquals(null, controller.cancel());
		System.assertNotEquals(null, controller.save());
	}
}