src/objects/Badge_Claim__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Ext_Id__c</fullName>
        <label>Contact Ext Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Badge Claims</relationshipLabel>
        <relationshipName>Badge_Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_City__c</fullName>
        <label>Town/City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Badge Claim</label>
    <nameField>
        <displayFormat>BC-{00000000}</displayFormat>
        <label>Badge Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Ext_Id__c</fullName>
        <externalId>true</externalId>
        <label>Contact Ext Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDF_BadgeClaimTriggerHandler.cls
@isTest
public with sharing class TestDF_BadgeClaimTriggerHandler {
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Test Class for DF_BadgeClaimTriggerHandler Trigger.
 *  Author  : Ian Smith
 *  Date    : 21-03-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:  Apex Class to test DF_BadgeClaimTriggerHandler trigger on the Badge_Claim__c object. 
 *               
 *  Modification History
 *  Date          Who      Description 
 *  dd-mm-yyyy    ??    ??
 *                             
*******************************************************************************************/

    static testMethod void testInsert(){
           
    //New DF_Contact__c Record to be added to the Badge_Claim__c test Data.
    DF_Contact__c df = new DF_Contact__c(Name='Test DFC', Contact_Ext_Id__c = 12345678
                                         ,First_Name__c = 'Test', Last_Name__c ='DFC'
                                         ,email__c= 'email'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alztest.com');
    insert df;
              
    //New Badge_Claim__c Record to be added to the test Data.
    Badge_Claim__c bc = new Badge_Claim__c(Town_City__c='Test City', Street__c='37 Test Street', DF_Contact__c=df.Id);
 
        //Now insert data causing the Badge_Claim__c trigger to fire. 
        Test.startTest();
    insert bc;
        Test.stopTest(); 
    }
    
    
    
  static testMethod void testBulkInsert(){
              
    //New DF_Contact__c Record to be added to the Badge_Claim__c test Data.
    DF_Contact__c df = new DF_Contact__c(Name='Test DFC', Contact_Ext_Id__c = 12345678
                                         ,First_Name__c = 'Test', Last_Name__c ='DFC'
                                         ,email__c= 'email'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alztest.com');
    insert df;
    
    //New Badge_Claim__c Record to be added to the test Data.
        Badge_Claim__c[] badgeClaimToCreate = new Badge_Claim__c[]{};
        
        //Create 200 new DF_Contact Records for a Bulk test.
        for(Integer i=0; i< 200; i++){
            Badge_Claim__c bc = new Badge_Claim__c(Town_City__c = 'Test City',
        Street__c='37 Test Street', 
        DF_Contact__c = df.Id
      );
            badgeClaimToCreate.add(bc);
        }
        
        //Now insert data causing the Badge_Claim__c trigger to fire. 
        Test.startTest();  
        insert badgeClaimToCreate;
        Test.stopTest();  
    }    
    
    
    
    static testMethod void testUpdate(){
      
    //New DF_Contact__c Record to be added to the Badge_Claim__c test Data.
    DF_Contact__c df = new DF_Contact__c(Name='Test DFC', Contact_Ext_Id__c = 12345678
                                             ,First_Name__c = 'Test', Last_Name__c ='DFC'
                                         ,email__c= 'email'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alztest.com');              
    insert df;
    
    //New Badge_Claim__c Record to be added to the test Data.
    Badge_Claim__c bc = new Badge_Claim__c(Town_City__c='Test City', Street__c='37 Test Street', DF_Contact__c=df.Id);
    insert bc;
    
    Test.startTest();  // Start Executing the test.

    bc.Town_City__c = 'TestCity';
    bc.Street__c = '36 Test Street';
    update bc;
            
        Test.stopTest();  // Stops the test execution.
                
        System.assertEquals('TestCity', [select Town_City__c from Badge_Claim__c where id =: bc.id].Town_City__c);
  }
  
  
  
  static testMethod void testBulkUpdate(){
      
    //New DF_Contact__c Record to be added to the Badge_Claim__c test Data.
    DF_Contact__c df = new DF_Contact__c(Name='Test DFC', Contact_Ext_Id__c = 12345678                                         ,First_Name__c = 'Test', Last_Name__c ='DFC'
                                         ,email__c= 'email'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alztest.com');              
    insert df;
    
    //New Badge_Claim__c Record to be added to the test Data.
        Badge_Claim__c[] badgeClaimToCreate = new Badge_Claim__c[]{};
        
        //Create 200 new DF_Contact Records for a Bulk test.
        for(Integer i=0; i< 200; i++){
            Badge_Claim__c bc = new Badge_Claim__c(Town_City__c = 'Test City',
        Street__c='37 Test Street', 
        DF_Contact__c=df.Id
      );
            badgeClaimToCreate.add(bc);
        }      
      
    List<Badge_Claim__c> lstToUpdate = [select Id, Town_City__c from Badge_Claim__c where Town_City__c = 'Test City'];
    for(Badge_Claim__c bc : lstToUpdate){
            bc.Street__c = 'TestStreet';
        }
   
    Test.startTest();  // Start Executing the test.   
    update lstToUpdate;
        Test.stopTest();  // Stops the test execution.
  }
    
    
    
    static testMethod void testDelete(){

    //New DF_Contact__c Record to be added to the Badge_Claim__c test Data.
    DF_Contact__c df = new DF_Contact__c(Name='Test DFC', Contact_Ext_Id__c = 12345678                                         ,First_Name__c = 'Test', Last_Name__c ='DFC'
                                         ,email__c= 'email'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alztest.com');              
    insert df;
    
    //New Badge_Claim__c Record to be added to the test Data.
    Badge_Claim__c bc = new Badge_Claim__c(Town_City__c='Test City', Street__c='37 Test Street', DF_Contact__c=df.Id);
    insert bc;
    
    Test.startTest();  // Start Executing the test.           
    delete bc;
    Test.stopTest();  // Stops the test execution.
  }   
}