src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Date_of_Champion_Training__c</fullName>
        <label>Date of Champion Training</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Last_Name__c &amp; &quot;,  &quot; &amp; First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospective</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hiatus/Resting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <label>Trainer</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF Contacts (Trainer)</relationshipLabel>
        <relationshipName>Trainer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Champion__c</fullName>
        <label>Type of Champion</label>
        <picklist>
            <picklistValues>
                <fullName>Super Champion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Champion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR Champion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children’s Champion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Champion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast tracked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor Champion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type 2</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <label>Trainer</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF Events (Trainer)</relationshipLabel>
        <relationshipName>DF_Events1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EventAttendeeStatus__c</fullName>
        <label>Event Attendee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <formula>DF_Event__r.Trainer__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trainer</label>
        <type>Text</type>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DfEventAttendeeController.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : 
 *  Author  : Venkat Akula
 *  Date    : 07/02/2013
 *  Version : 1
 *
 *  Description: Controller for the DF Event Attendee Page.  
 *               Allows user to update the status of the attendees at a DF Champions Training meeting.   
 *                  
 *               
 *  Modification History
 *  Date            Who         Description 
 *  07/03/2014      Sri Tadikonda        Add Champion Status
 *  11/04/2014      CSL         Removed the Trainer__c field from DF_Contact__c as per Ian Smith 11/04/2014
 *  14/04/2014      Mike Tinson Add Page header so user knows which event is being processed.
 *  17/04/2014		Mike Tinson	Check that records have not been updated by someone else after page has been loaded.
 ******************************************************************************************/
Public Class DfEventAttendeeController
{
    Private Final DF_Event__c dfEvent;
    Public String EventTitle {get;set;}
    
    List<DF_EventAttendee__c> listEventAttendees;
    List<DF_EventAttendee__c> listCurrentEventAttendees;
    List<DF_Contact__c> listDFContacts;
    List<Id> contactIds = new List<Id>();
    //DF_Event__c dfeventnew;
    
    public DfEventAttendeeController(ApexPages.StandardController stdController)
    {
        this.dfEvent= (DF_Event__c)stdController.getRecord();
        
        Id dfEventId = dfEvent.Id;
        DF_Event__c dfEventRec = [Select id, name from DF_Event__c  where id=:dfEventId ];
        EventTitle = dfEventRec.Name;
        //get list of attendees for the current event.
        listEventAttendees = (List<DF_EventAttendee__c>)[Select Id, Name, DF_Contact__r.Name, DF_Event__c, 
                       DF_Contact__r.Contact_Number__c,DF_EventAttendee__c.DF_Contact__r.Status__c,DF_EventAttendee__c.DF_Contact__r.Email__c,
                       DF_EventAttendee__c.DF_Contact__r.Name__c,DF_Event__r.Session_Organiser__c,EventAttendeeStatus__c, DF_Event__r.Trainer__c,
                       DF_Event__r.Event_Date_Time__c,DF_Contact__r.Type_of_Champion__c, LastModifiedDate,DF_Contact__r.LastModifiedDate 
                       FROM DF_EventAttendee__c Where DF_Event__c = : dfEventId];
       //standard sort order 
       listEventAttendees.sort();
       
       for(DF_EventAttendee__c rec:listEventAttendees)
       {
           contactIds.add(rec.DF_Contact__c);
       }
        //2014-04-11 : CSL : Removed Trainer__c field from DF_Contact__c
        //listDFContacts = [Select Name,Status__c,Email__c,Trainer__c,Type_of_Champion__c,Date_of_Champion_Training__c, Contact_Number__c FROM DF_Contact__c Where DF_Contact__c.Id IN:contactIds]; 
        listDFContacts = [Select Name,Status__c,Email__c,Type_of_Champion__c,Date_of_Champion_Training__c, Contact_Number__c FROM DF_Contact__c Where DF_Contact__c.Id IN:contactIds];
                                                            
    }                                                          
    public List<DF_EventAttendee__c> getListEventAttendees()
    {
        return listEventAttendees;
    }
    
    public Pagereference save()
    {
        //re-read event records to get current modified date
        
        listCurrentEventAttendees = (List<DF_EventAttendee__c>)[Select Id
        														, Name
        														, LastModifiedDate
        														, DF_Contact__r.LastModifiedDate 
        														FROM DF_EventAttendee__c 
        														WHERE  DF_Event__c =:dfEvent.Id];
        
        //update date of training on Contact record.
        //also check for simulatious update on record.
        for(DF_EventAttendee__c rec :listEventAttendees)
        {
            for(DF_Contact__c dfContact: listDFContacts)
            {
                if(rec.DF_Contact__c == dfContact.Id)
                {
                     if(rec.DF_Contact__r.Status__c == 'Converted')
                     {
                         dfContact.Status__c = rec.DF_Contact__r.Status__c;                       
                         dfContact.Date_of_Champion_Training__c = rec.DF_Event__r.Event_Date_Time__c.date();
                         //2014-04-11 : CSL : Removed Trainer__c field from DF_Contact__c
                         //dfContact.Trainer__c = rec.DF_Event__r.Session_Organiser__c;
                         dfContact.Type_of_Champion__c = rec.DF_Contact__r.Type_of_Champion__c;    
                     }
                     else
                     {
                         dfContact.Status__c = rec.DF_Contact__r.Status__c;
                         dfContact.Date_of_Champion_Training__c = NULL;
                         //2014-04-11 : CSL : Removed Trainer__c field from DF_Contact__c
                         //dfContact.Trainer__c = NULL;
                         dfContact.Type_of_Champion__c = NULL;
                     }
                     break;
                }
            }
            for (DF_EventAttendee__c dfCurrentEA: listCurrentEventAttendees)
            {
            	//Compare Last Modified date on Event Attendee record AND the DF contact record.  If there has been a change on either raise an error and do not proceed.
                if (rec.Id == dfCurrentEA.Id){
                    if ((rec.LastModifiedDate.format('yyyy-MM-dd HH:mm:ss.SSS') <> dfCurrentEA.LastModifiedDate.format('yyyy-MM-dd HH:mm:ss.SSS'))||
                    	(rec.DF_Contact__r.LastModifiedDate.format('yyyy-MM-dd HH:mm:ss.SSS') <> dfCurrentEA.DF_Contact__r.LastModifiedDate.format('yyyy-MM-dd HH:mm:ss.SSS'))){
                        system.debug ('££££££££££ record update clash ' + rec.id + ' ' + rec.DF_Contact__r.Name );
                        ApexPages.Message message = new ApexPages.message(ApexPages.severity.ERROR,'An error occurred while saving event attendees.: One or more records have been updated by another user.' + 
                                                                            ' Please re-display the records before editing again.') ;
                        ApexPages.addMessage(message);
                        return null;
                    }
                }   
                
            }
        }
        SavePoint sp=Database.setSavePoint();
        try{
            update listDFContacts;
            update listEventAttendees;
            return (new ApexPages.StandardController(dfEvent)).view();
        }
        catch (Exception ex){ 
                Database.rollback(sp);
                String msg=ex.getMessage();
                ApexPages.Message message = new ApexPages.message(ApexPages.severity.ERROR,'An error occurred while saving event attendees.: ' + msg);
                ApexPages.addMessage(message);
                return null;
            }
    }

}