src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attended?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Number of Places</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Champion_Training_Course</fullName>
        <active>true</active>
        <description>Events organised by Alzheimers Society/Trusted Partners</description>
        <label>Champion Training Course</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Awareness_Session</fullName>
        <active>true</active>
        <description>Events organised by DF Champions</description>
        <label>Dementia Friend Awareness Session</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EventAttendeeStatus__c</fullName>
        <label>Event Attendee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Attendee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

src/classes/TestDFContactAttendeeFlagPhase1.cls
/**
 * 2014-08-01 : CSL : This class is to test the DFContactAttendeeFlagPhase1 Batch class
 * 
 */
@isTest
private class TestDFContactAttendeeFlagPhase1 {
	
	private static String RANDOM_STRING = String.valueOf(system.now().format('yyyyMMddHHmmssSSS')) + String.valueOf(Crypto.getRandomInteger()).substring(1,4);
	private static String EMAIL_ADDRESS = RANDOM_STRING + '_dummy@test.com';
	private static String PASSWORD = 'Qwerty12345';
	private static String FRIEND_RT_NAME = 'Dementia_Friend';
	private static String CHAMPION_RT_NAME = 'Dementia_Friend_Champion';
	private static String SESSION_RT_NAME = 'Dementia_Friend_Awareness_Session';
	private static String TRAINING_RT_NAME = 'Champion_Training_Course';
	private static User adminUser;
	private static User guestUser;
	private static User portalUser;
	private static Contact contactRecord;
	private static Contact soContactRecord;
	private static DF_Contact__c sessionOrganiser;
	private static DF_Contact__c dfContactRecord;
	private static DF_Event__c testSession;
	private static DF_Event__c testTraining;
	
    private static void setUpSystemData(){
		RecordType dfcFriend = [select r.Id from RecordType r where r.DeveloperName = :FRIEND_RT_NAME and r.SobjectType = 'DF_Contact__c' and IsActive = true LIMIT 1];
		RecordType cFriend = [select r.Id from RecordType r where r.DeveloperName = :FRIEND_RT_NAME and r.SobjectType = 'Contact' and IsActive = true LIMIT 1];
		RecordType dfcChampion = [select r.Id from RecordType r where r.DeveloperName = :CHAMPION_RT_NAME and r.SobjectType = 'DF_Contact__c' and IsActive = true LIMIT 1];
		RecordType cChampion = [select r.Id from RecordType r where r.DeveloperName = :CHAMPION_RT_NAME and r.SobjectType = 'Contact' and IsActive = true LIMIT 1];
		
		adminUser = [Select Id From User Where Profile.Name='System Administrator' And IsActive=true limit 1];
		guestUser = [Select Id From User Where UserType='Guest' limit 1];
		portalUser = [Select Id, ContactId from User where Profile.Name='DF HVCP' and IsActive = true LIMIT 1];
		contactRecord = [Select FirstName, LastName, Email from Contact where Id = :portalUser.ContactId LIMIT 1];
		soContactRecord = [Select FirstName, LastName, Email from Contact where RecordTypeId = :cChampion.Id LIMIT 1];
		
    	Global_Setting__c setting = Global_Setting__c.getInstance('webAccountOwnerId');
    	if (setting == null){
    		setting = new Global_Setting__c(Name='webAccountOwnerId',Value__c=adminUser.Id);
        	insert setting;
    	}
    	List<DF_Contact__c> dfConList = new List<DF_Contact__c>();
    	dfConList = [select d.First_Name__c, d.Last_Name__c, d.Email__c, d.RecordTypeId, d.Portal_Contact__c from DF_Contact__c d where d.Portal_Contact__c = :contactRecord.Id LIMIT 1];
    	if (dfConList.size() == 0){
	    	dfContactRecord = new DF_Contact__c();
	    	dfContactRecord.RecordTypeId = [select r.Id from RecordType r where r.DeveloperName = :CHAMPION_RT_NAME and r.SObjectType = 'DF_Contact__c' LIMIT 1].Id;
	    	dfContactRecord.Portal_Contact__c = portalUser.ContactId;
	    	dfContactRecord.First_Name__c = contactRecord.FirstName;
	    	dfContactRecord.Last_Name__c = contactRecord.LastName;
	    	dfContactRecord.Email__c = contactRecord.Email;
	    	if (dfContactRecord.Email__c == null) dfContactRecord.Email__c = 'test.email@myemail.com';
	    	dfContactRecord.Attended__c = true;
	    	insert dfContactRecord;
    	}else {
    		dfContactRecord = dfConList[0];
    	}
    	
    	List<DF_Contact__c> soDFConList = new List<DF_Contact__c>();
    	soDFConList = [select d.First_Name__c, d.Last_Name__c, d.Email__c, d.RecordTypeId, d.Portal_Contact__c from DF_Contact__c d where d.Portal_Contact__c = :soContactRecord.Id LIMIT 1];
    	if (soDFConList.size() == 0){
    		sessionOrganiser = new DF_Contact__c();
	    	sessionOrganiser.RecordTypeId = [select r.Id from RecordType r where r.DeveloperName = :CHAMPION_RT_NAME and r.SObjectType = 'DF_Contact__c' LIMIT 1].Id;
	    	sessionOrganiser.Portal_Contact__c = soContactRecord.Id;
	    	sessionOrganiser.First_Name__c = soContactRecord.FirstName;
	    	sessionOrganiser.Last_Name__c = soContactRecord.LastName;
	    	sessionOrganiser.Email__c = soContactRecord.Email;
	    	insert sessionOrganiser;
    	}else {
    		sessionOrganiser = soDFConList[0];
    	}
    	
    	testSession = new DF_Event__c();
    	testSession.RecordTypeId = [select r.Id from RecordType r where r.DeveloperName = :SESSION_RT_NAME and r.IsActive = true and r.SObjectType = 'DF_Event__c' LIMIT 1].Id;
    	testSession.Name = 'Test Session';
    	testSession.Event_Date_Time__c = DateTime.now().addDays(7);
    	testSession.Event_Status__c = 'Available';
    	testSession.Number_of_Places__c = 10;
    	testSession.Session_Organiser__c = sessionOrganiser.Id;
    	insert testSession;
    	
    	testTraining = new DF_Event__c();
    	testTraining.RecordTypeId = [select r.Id from RecordType r where r.DeveloperName = :TRAINING_RT_NAME and r.IsActive = true and r.SObjectType = 'DF_Event__c' LIMIT 1].Id;
    	testTraining.Name = 'Test Training';
    	testTraining.Event_Date_Time__c = DateTime.now().addDays(7);
    	testTraining.Event_Status__c = 'Available';
    	testTraining.Number_of_Places__c = 10;
    	testTraining.Session_Organiser__c = sessionOrganiser.Id;
    	insert testTraining;
    	
	}
	/*
	@IsTest(SeeAllData=true)
    static void testSessionTrigger() {
		setupSystemData();
		
		system.debug('*** -- Test Code Debug - ' + dfContactRecord.Portal_Contact__c + ' -- ***');
		
		DF_EventAttendee__c dfe1 = new DF_EventAttendee__c();
		dfe1.DF_Contact__c = dfContactRecord.Id;
		dfe1.DF_Event__c = testSession.Id;
		system.debug('*** -- Test Code Debug 2 - ' + dfe1.DF_Contact__r.Portal_Contact__c + ' -- ***');
		//This should fire the first trigger
		test.startTest();
		insert dfe1;
		test.stopTest();
		delete dfe1;
		
		    	
    }
    */
    @IsTest(SeeAllData=true)
    static void testBatchPhase1() {
		setupSystemData();
		
		system.debug('*** -- Test Code Debug - ' + dfContactRecord.Portal_Contact__c + ' -- ***');
		
		DF_EventAttendee__c dfe1 = new DF_EventAttendee__c();
		dfe1.DF_Contact__c = dfContactRecord.Id;
		dfe1.DF_Event__c = testTraining.Id;
		system.debug('*** -- Test Code Debug 2 - ' + dfe1.DF_Contact__r.Portal_Contact__c + ' -- ***');
		//This should fire the first trigger
		insert dfe1;
		
		test.startTest();
		
		RecordType rt = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'Dementia Friend Champion' AND isActive = TRUE];
		String query = 'SELECT d.Name, d.Id, d.Attended__c, d.Note__c, (Select Id, Event_Status__c, EventAttendeeStatus__c, DF_Event__r.Name From DF_EventAttendees__r) From DF_Contact__c d where d.Attended__c = true and d.RecordTypeId = \'' + rt.Id + '\' LIMIT 200';
		
		
		DFContactAttendeeFlagPhase1 dfcafp1 = new DFContactAttendeeFlagPhase1();
		dfcafp1.query = query;
		
		Database.executeBatch(dfcafp1);
		
		test.stopTest();		    	
    }
}