src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Verefied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User Code Verefied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Code_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Session Code Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>DFC_Code__c</fullName>
        <label>DFC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Registration_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to hold the registration codes for Friends &amp; Champions</description>
    <fields>
        <fullName>Code_Value__c</fullName>
        <label>Code Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Registration Code</label>
</CustomObject>

src/classes/WEBConversionClassTest.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX test class for WEBConversionClass.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex test class.
 *               
 *  Modification History
 *  Date            Who         Description 
 *                    
*******************************************************************************************/
@isTest 
public with sharing class WEBConversionClassTest {
	
	private static testMethod void testWEBConversionClass1(){
		
		Registration_Code__c setting = Registration_Code__c.getInstance('Champion');
    	if (setting == null){
    		setting = new Registration_Code__c(Name='Champion',Code_Value__c='ABC123');
        	insert setting;
    	}
    	
    	Registration_Code__c setting1 = Registration_Code__c.getInstance('Friend');
    	if (setting1 == null){
    		setting1 = new Registration_Code__c(Name='Friend',Code_Value__c='DEMENTIAFRIEND123');
        	insert setting1;
    	}
    	
    	Partner_Organisation__c po = new Partner_Organisation__c();
    	po.Name = 'Alzheimers Society';
    	po.DFC_Code__c = 'ABC123';
    	insert po;
    	
		Account a = new Account(Name='Test Account Name');
  		insert a;
        
        Contact c = new Contact();
        c.firstname = 'Test';
        c.LastName = 'TestContact';
        c.AccountId = a.Id;
        c.Email = 'test.testcontact@myemail.com';
        c.RecordTypeId = [Select Id From RecordType Where DeveloperName=:WEBConversionClass.RT_CONTACT_FRIEND And sObjectType='Contact'].Id;
        insert c;
            
        Profile profileForUser = [SELECT Id FROM Profile WHERE Name='DF HVCP']; 
		
		User user1 = new User(Alias = 'standt',Email='light@testorg.com',EmailEncodingKey='UTF-8',LastName='Testing', LanguageLocaleKey='en_US', 
                        	  LocaleSidKey='en_US', ProfileId = profileForUser.Id, TimeZoneSidKey='America/Los_Angeles',UserName=Math.random() + '@test.com',ContactId =c.id );
        insert user1;   
        
        DF_Contact__c DFc = new DF_Contact__c();
        DFc.RecordTypeId = [Select Id From RecordType Where DeveloperName=:WEBConversionClass.RT_CONTACT_CHAMPION And sObjectType='DF_Contact__c'].Id;
        DFc.First_Name__c = c.FirstName;
        DFc.Last_Name__c = c.LastName;
        DFc.Email__c = c.Email;
        DFc.Portal_Contact__c = c.Id;
        insert DFc;
       	
       	DF_Event__c dfevents= new DF_Event__c();
       	dfevents.Location__c = 'Test';
	   	dfevents.Event_Date_Time__c = system.today();
		dfevents.Street__c = 'Test';
		dfevents.City__c = 'Test';
		dfevents.County__c = 'Test';
		dfevents.Country__c = 'Test';
		dfevents.Postcode__c = 'Test';
		dfevents.Session_Organiser__c = DFc.Id;
		insert dfevents;
        
        system.runAs(user1) {	
        	system.currentPageReference().getParameters().put('event', dfevents.Id);
        	WEBConversionClass conversionClass = new WEBConversionClass();
        	WEBConversionClass.friendConvertCode = 'DEMENTIAFRIEND123';
        	WEBConversionClass.championConvertCode = 'ABC123';
        	WEBConversionClass.contactToBeConverted = c;
        	WEBConversionClass.dfContactToBeConverted = DFc;
        	
        	String s = WEBConversionClass.whatIsAChampionPage;
        	Boolean b1 = WEBConversionClass.isFriend(c.Id);
        	Boolean b2 = WEBConversionClass.isChampion(c.Id);
        	Boolean b3 = WEBConversionClass.convertToFriend(c.Id, WEBConversionClass.friendConvertCode);
        	Boolean b4 = WEBConversionClass.convertFriendToChampion(c.Id, WEBConversionClass.championConvertCode);
        	DFc.Code_Verefied__c = true;
        	DFc.Session_Code_Verified__c = true;
        	update DFc;
        	DFc = [SELECT Id,Code_Verefied__c, Session_Code_Verified__c FROM DF_Contact__c WHERE Portal_Contact__c=:c.Id ];
        	
        	Boolean b5 = WEBConversionClass.convertChampionToFriend(c.Id, WEBConversionClass.friendConvertCode);
        	Boolean b6 = WEBConversionClass.convertFriendToChampion(c.Id, WEBConversionClass.championConvertCode);
        }
	}
	
	private static testMethod void testWEBConversionClass2(){
		
		Partner_Organisation__c po = new Partner_Organisation__c();
    	po.Name = 'Alzheimers Society';
    	po.DFC_Code__c = 'ABC123';
    	insert po;
		
		Registration_Code__c setting = Registration_Code__c.getInstance('Champion');
    	if (setting == null){
    		setting = new Registration_Code__c(Name='Champion',Code_Value__c='ABC123');
        	insert setting;
    	}
    	
    	Registration_Code__c setting1 = Registration_Code__c.getInstance('Friend');
    	if (setting1 == null){
    		setting1 = new Registration_Code__c(Name='Friend',Code_Value__c='DEMENTIAFRIEND123');
        	insert setting1;
    	}
		
		Account a = new Account(Name='Test Account Name');
  		insert a;
        
        Contact c = new Contact();
        c.firstname = 'Test';
        c.LastName = 'TestContact';
        c.AccountId = a.Id;
        c.Email = 'test.testcontact@myemail.com';
        c.RecordTypeId = [Select Id From RecordType Where DeveloperName=:WEBConversionClass.RT_CONTACT_CHAMPION And sObjectType='Contact'].Id;
        insert c;
            
        Profile profileForUser = [SELECT Id FROM Profile WHERE Name='DF HVCP']; 
		
		User user1 = new User(Alias = 'standt',Email='light@testorg.com',EmailEncodingKey='UTF-8',LastName='Testing', LanguageLocaleKey='en_US', 
                        	  LocaleSidKey='en_US', ProfileId = profileForUser.Id, TimeZoneSidKey='America/Los_Angeles',UserName=Math.random() + '@test.com',ContactId =c.id );
        insert user1;   
        
       DF_Contact__c DFc = new DF_Contact__c();
        DFc.RecordTypeId = [Select Id From RecordType Where DeveloperName=:WEBConversionClass.RT_CONTACT_CHAMPION And sObjectType='DF_Contact__c'].Id;
        DFc.First_Name__c = c.FirstName;
        DFc.Last_Name__c = c.LastName;
        DFc.Email__c = c.Email;
        DFc.Portal_Contact__c = c.Id;
        insert DFc;
       	
       	DF_Event__c dfevents= new DF_Event__c();
       	dfevents.Location__c = 'Test';
	   	dfevents.Event_Date_Time__c = system.today();
		dfevents.Street__c = 'Test';
		dfevents.City__c = 'Test';
		dfevents.County__c = 'Test';
		dfevents.Country__c = 'Test';
		dfevents.Postcode__c = 'Test';
		dfevents.Session_Organiser__c = DFc.Id;
		
		insert dfevents;
        
        system.runAs(user1) {	
        	system.currentPageReference().getParameters().put('event', dfevents.Id);
        	WEBConversionClass conversionClass = new WEBConversionClass();
        	WEBConversionClass.friendConvertCode = 'DEMENTIAFRIEND123';
        	WEBConversionClass.championConvertCode = 'ABC123';
        	WEBConversionClass.contactToBeConverted = c;
        	WEBConversionClass.dfContactToBeConverted = DFc;
        	
        	
        	
        	Boolean b1 = WEBConversionClass.isFriend(c.Id);
        	Boolean b2 = WEBConversionClass.isChampion(c.Id);
        	Boolean b3 = WEBConversionClass.convertToFriend(c.Id, WEBConversionClass.friendConvertCode);
        	Boolean b4 = WEBConversionClass.registerAsChampion(user1.ContactId);
        	Boolean b5 = WEBConversionClass.convertFriendToChampion(c.Id, WEBConversionClass.championConvertCode);
        	DFc.Code_Verefied__c = true;
        	DFc.Session_Code_Verified__c = true;
        	update DFc;
        	DFc = [SELECT Id,Code_Verefied__c, Session_Code_Verified__c FROM DF_Contact__c WHERE Portal_Contact__c=:c.Id ];
        	
        	Boolean b6 = WEBConversionClass.convertChampionToFriend(c.Id, WEBConversionClass.friendConvertCode);
        	Boolean b7 = WEBConversionClass.convertToChampion(c.Id);
        	
        }
	}

}