src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attended?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contacted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contacted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospective</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hiatus/Resting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Description__c</fullName>
        <label>Event Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <label>Number of Attendees</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Number of Places</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEBChampionSessionFeedback.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX controller class for VF Page WEBChampionSessionFeedback.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex Class controller for the WEBChampionSessionFeedback class.
 *					This is used to create Session Feedback records for DF Events
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/
public with sharing class WEBChampionSessionFeedback extends WEBController {
    
    public final String STATUS_CANCELLED = 'Cancelled';
    public final String STATUS_CLOSED = 'Closed';
    
    
    public Boolean isChampion {get;set;}
    public Boolean isConverted {get; set;}
    
    public String messageArea {get;set;}
    public String messageAreaClass {get;set;}

	//2014-05-19 : CSL : Adding in totalFriendsSnippet for display on the VF page
	public Page_Snippet__c totalFriendsSnippet {
		get {
			if (totalFriendsSnippet == null){
				totalFriendsSnippet = [select p.Body_Text__c, p.Unique_Name__c from Page_Snippet__c p where p.Unique_Name__c = 'DementiaFriendsTotalSnippet' LIMIT 1];
			}
			return totalFriendsSnippet;
		}
		set ;
	}

    public DF_Event__c event {
        get {
            if (event == null)
                event = new DF_Event__c();
            return event;
        }
        set;
    }

    public List<SelectOption> sessionList {
        get {
            if (sessionList == null)
                sessionList = new List<SelectOption>();
            return sessionList;
        }
        set;
    }

    public Integer sessionListSize {
        get {
            return sessionList.size();
        }
        set;
    }

    public Boolean thereAreNoSessions {get;set;}

    public String selectedSession {get;set;}

    public Integer noOfAttendees {get;set;}
    public String sessionComments {get;set;}

    public List<DF_Event__c> eventsRequiringFeedback {
        get {
            if (eventsRequiringFeedback == null)
                eventsRequiringFeedback = new List<DF_EVENT__c>();
            
            return eventsRequiringFeedback;
        }
        set;
    }

	//Save method
    public PageReference save() {

        if (event.Id == null && selectedSession != null) {
            event = [SELECT Id, Name, Event_Description__c, Comments__c, Number_of_Attendees__c
                        FROM DF_Event__c
                        WHERE Id = :selectedSession];
        }

        if (event != null) {
            event.Number_of_Attendees__c = noOfAttendees;
            event.Comments__c = sessionComments;
            
            upsert event;
        }
        
        return Page.WEBChampionManageMySessions;
    }
    
    public PageReference cancelSession() {
    	if (event.Id == null && selectedSession != null) {
            event = [SELECT Id, Name, Event_Description__c, Comments__c, Number_of_Attendees__c, Event_Status__c
                        FROM DF_Event__c
                        WHERE Id = :selectedSession];
        }

        if (event != null) {
            event.Event_Status__c = 'Cancelled';
            event.Comments__c = sessionComments;
            
            upsert event;
        }
        
        return Page.WEBChampionManageMySessions;
    }

	//Constructor
    public WEBChampionSessionFeedback() {
        noOfAttendees = 0;
        sessionComments = '';
        thereAreNoSessions = FALSE;

        isChampion = WEBController.isChampion;
        isConverted = WEBController.isChampionConverted;

        String currentSession = ApexPages.currentPage().getParameters().get('eventId');

        if (currentSession != null) {
            System.debug('*** Found Event Parameter ' + currentSession);
                
            event = [SELECT Id, Name, Event_Description__c, Comments__c, Number_of_Attendees__c
                        FROM DF_Event__c
                        WHERE Id = :currentSession];

            if (event != null) {
                if (event.Number_of_Attendees__c != null)
                    noOfAttendees = event.Number_of_Attendees__c.intValue();
                if (event.Comments__c != null)
                    sessionComments = event.Comments__c;
            } else {
                thereAreNoSessions = TRUE;
            }
        } else {
            // Must be choosing multiple sessions
			
			eventsRequiringFeedback = new List<DF_Event__c>();
			for (DF_Event__c dfe : [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c 
									FROM DF_Event__c WHERE Session_Organiser__r.Portal_Contact__r.Id = :WEBController.thisUser.ContactId 
									AND Event_Date_Time__c <= TODAY 
									AND (Number_of_Attendees__c = null OR Number_of_Attendees__c = 0) 
									and (Event_Status__c != :STATUS_CANCELLED AND Event_Status__c != :STATUS_CLOSED) ORDER BY Event_Date_Time__c DESC LIMIT 10]){
				
				if (dfe.Event_Date_Time__c.getTime() < system.now().getTime()){
					eventsRequiringFeedback.add(dfe);
				}
			}
			
			//2014-05-21 : CSL : Changing this SOQL statement temporarily to show the 'Report On Event' screen
            //eventsRequiringFeedback = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c FROM DF_Event__c WHERE Session_Organiser__r.Portal_Contact__r.Id = :WEBController.thisUser.ContactId AND Event_Date_Time__c < TODAY AND (Number_of_Attendees__c = null OR Number_of_Attendees__c = 0) and Event_Status__c != :STATUS_CANCELLED LIMIT 10];
            //TEST CODE
            //eventsRequiringFeedback = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c FROM DF_Event__c WHERE Session_Organiser__r.Portal_Contact__r.Id = :WEBController.thisUser.ContactId AND Event_Date_Time__c <= TODAY LIMIT 10];
            if (eventsRequiringFeedback == null || eventsRequiringFeedback.size() == 0) {
                thereAreNoSessions = TRUE;

                return;
            }

            for (DF_Event__c sess : eventsRequiringFeedback) {
                SelectOption s = new SelectOption(sess.Id, sess.Name + ' ' + sess.Event_Date_Time__c.format('dd/MM/yyyy'));
                sessionList.add(s);
            }
        }
        
    }
    
    //Test methods
	 public testmethod static void tesWEBChampionFeedback(){
	 	
	   DF_Contact__c dfcon = new DF_Contact__c(Name='Test dfcontact',First_Name__c='Test',Last_Name__c='dfcontact',Status__c='Prospective',Email__c='test@dfcon.com',
	   RecordTypeId=[Select Id from RecordType where SObjectType='DF_Contact__c' and Name Like 'Dementia Friend Champion'].Id,
	                                            Contact_Number__c='12345678',Eligible__c=FALSE,Contacted__c=FALSE,
	                                            Attended__c=FALSE,Note__c='Test Notes');
	    insert dfcon;
	    
	   DF_Event__c evnt = new DF_Event__c(Name='test12',Event_Description__c='test Description',Event_Status__c='Available',Event_Date_Time__c=system.now(),Street__c='teststreet',City__c='testcity',County__c='uk',Postcode__c='12345678912',Number_of_Places__c=1234,
	                               Session_Organiser__c=dfcon.id,Comments__c ='testcommetns',Number_of_Attendees__c=1234); 
	   insert evnt;
	   
	   ApexPages.currentPage().getParameters().put('eventId', evnt.id);
	   
	   WEBChampionSessionFeedback webfeedback = new WEBChampionSessionFeedback();
	   webfeedback.save();
	    
	 }
	 public testmethod static void tesWEBChampionFeedbacktwo(){
	 	
	   DF_Contact__c dfcon = new DF_Contact__c(Name='Test dfcontact',First_Name__c='Test',Last_Name__c='dfcontact',Status__c='Prospective',Email__c='test@dfcon.com',
	   RecordTypeId=[Select Id from RecordType where SObjectType='DF_Contact__c' and Name Like 'Dementia Friend Champion'].Id,
	                                            Contact_Number__c='12345678',Eligible__c=FALSE,Contacted__c=FALSE,
	                                            Attended__c=FALSE,Note__c='Test Notes');
	    insert dfcon;
	    
	   DF_Event__c evnt = new DF_Event__c(Name='test12',Event_Description__c='test Description',Event_Status__c='Available',Event_Date_Time__c=system.now(),Street__c='teststreet',City__c='testcity',County__c='uk',Postcode__c='12345678912',Number_of_Places__c=1234,
	                               Session_Organiser__c=dfcon.id,Comments__c ='testcommetns',Number_of_Attendees__c=1234); 
	   insert evnt;
	   
	  // ApexPages.currentPage().getParameters().put('eventId', evnt.id);
	   
	   WEBChampionSessionFeedback webfeedback = new WEBChampionSessionFeedback();
	   webfeedback.selectedSession = evnt.id;
	   webfeedback.save();
	    
	 }
}