src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>RSO</fullName>
        <active>true</active>
        <label>RSO</label>
    </recordTypes>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Ext_Id__c</fullName>
        <externalId>true</externalId>
        <label>Contact Ext Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordType Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regional_Support_Officer__c</fullName>
        <label>Regional Support Officer</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>RSO</fullName>
        <active>true</active>
        <description>Regional Support Officer</description>
        <label>RSO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RSO_AreaLookup__c.object
<CustomObject>
    <description>Regional Support Officers (RSOs) who run Dementia Friend training with the postcode areas they cover.</description>
    <fields>
        <fullName>DFContactId__c</fullName>
        <inlineHelpText>Name of RSO</inlineHelpText>
        <label>Regional Support Officer</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>RSO Area Lookups</relationshipLabel>
        <relationshipName>RSO_Area_Lookups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode_Supported__c</fullName>
        <inlineHelpText>Enter a list of postcodes this RSO supports.  Enter the one or two letters of the postal area</inlineHelpText>
        <label>Postcodes Supported</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RSO Area Lookup</label>
    <nameField>
        <label>RSO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSO Area Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDFRegionalSupportOfficerReassignment.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Updates RSO for selected DF Contact records
 *  Author  : Mike Tinson
 *  Date    : 23 April 2014
 *  Version : 1
 *
 *  Description:  Test Class for DFRegionalSupportOfficerReassignment batch class.  
 *               
 *  Modification History
 *  Date            Who         Description 
 *  
 *  
 ******************************************************************************************/
@isTest
public class TestDFRegionalSupportOfficerReassignment  {

static testMethod void mainTest(){
        //record for champion
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'Dementia Friend Champion' AND isActive = TRUE];
        //record for RSO
        RecordType rtRSO = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'RSO' AND isActive = TRUE];

        //RSO
        DF_Contact__c dfRSO = new DF_Contact__c(Name='Test RSO',First_Name__c = 'Test', Last_Name__c ='RSO', Postcode__c='NW1 2XX', recordtypeid=rtRSO.id, Email__c='test.test'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alzheimers.org.uk');
        insert dfRSO;
        
        //RSO Area Lookup
        RSO_AreaLookup__c dfAreaLookup = new RSO_AreaLookup__c(Name='Test RSO',DFContactId__c=dfRSO.id,Postcode_Supported__c='NW,SE');
        insert dfAreaLookup; 

        //New DF_Contact__c Record to be added to the test Data.
        DF_Contact__c df = new DF_Contact__c(Name='Test DFC',First_Name__c = 'Test', Last_Name__c ='DFC', 
                                            Contact_Ext_Id__c = 12345678, Postcode__c='NW1 2XX', recordtypeid=rt.id, Email__c='test.testDFC'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alzheimers.org.uk');

        insert df;
        Test.StartTest();

        String query =  'select id, name, PostCode__c, Regional_Support_Officer__c, Email__c from DF_Contact__c  WHERE RecordType_Name__c = \'Dementia Friend Champion\' and id =\'' + df.id + '\''; 
        System.Debug('###query### ' + query);
        
        DFRegionalSupportOfficerReassignment  dfRSOReassign = new DFRegionalSupportOfficerReassignment ();
        dfRSOReassign.query= query;
        dfRSOReassign.email='crssupport@alzheimers.org.uk';
        ID batchprocessid = Database.executeBatch(dfRSOReassign);
        Test.StopTest();

 
}           


}