src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Description__c</fullName>
        <label>Event Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Number of Places</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Champion_Training_Course</fullName>
        <active>true</active>
        <description>Events organised by Alzheimers Society/Trusted Partners</description>
        <label>Champion Training Course</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Awareness_Session</fullName>
        <active>true</active>
        <description>Events organised by DF Champions</description>
        <label>Dementia Friend Awareness Session</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Attendee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

src/objects/Saved_Search__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <label>Post Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Range__c</fullName>
        <label>Range</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sent_Mail__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether the mail is sent or not to the user</inlineHelpText>
        <label>Sent Mail</label>
        <type>Checkbox</type>
    </fields>
    <label>Saved Search</label>
    <nameField>
        <displayFormat>Search-{0000}</displayFormat>
        <label>Saved Searches Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Searches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_DFEventTriggerMethods.cls
@isTest
private class Test_DFEventTriggerMethods{
	
	private static String FRIEND_RT_NAME = 'Dementia_Friend';
	private static String CHAMPION_RT_NAME = 'Dementia_Friend_Champion';
	private static String SESSION_RT_NAME = 'Dementia_Friend_Awareness_Session';
	private static String TRAINING_RT_NAME = 'Champion_Training_Course';
	private static String STATUS_CANCELLED = 'Cancelled';
	
	private static User adminUser;
	private static User guestUser;
	private static User portalUser;
	private static Contact contactRecord;
	private static Contact soContactRecord;
	private static DF_Contact__c sessionOrganiser;
	private static DF_Contact__c dfContactRecord;
	private static DF_Event__c testSession;
	private static DF_Event__c testTraining;
	private static DF_EventAttendee__c dfe1;

     
     @isTest static void testDFEventTriggerMethods() {
        try{
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseDFeventGenerator());        
           
            Saved_Search__c ssavedsearch= new Saved_Search__c();
            ssavedsearch.Post_Code__c = '560033';
            ssavedsearch.Email__c = 'test@gmail.com';
            ssavedsearch.Sent_Mail__c= false;
            ssavedsearch.Range__c = 5;
            ssavedsearch.Geolocation__Latitude__s = 30;
            ssavedsearch.Geolocation__Longitude__s = 30;
            insert ssavedsearch;
            
            DF_Contact__c contact = new DF_Contact__c();
            contact.First_Name__c = 'simon';
            contact.Last_Name__c= 'molloy';
            contact.Name = 'simonm';
            insert contact;
            
            DF_Event__c dfevent= new DF_Event__c();
            dfevent.Postcode__c = '560033';
            dfevent.Location_Geographic_Details__Latitude__s = 30;
            dfevent.Location_Geographic_Details__Longitude__s = 30;
            dfevent.Session_Organiser__c = contact.id;
            insert dfevent;
            
            DF_Event__c dfevent1 = new DF_Event__c();
            dfevent1.Postcode__c = '516001';
            dfevent1.Session_Organiser__c = contact.id;
            insert dfevent1;
            
            
            Set<Id> dfeventIds = new Set<Id>();
            dfeventIds.add(dfevent.Id);            
            dfeventIds.add(dfevent1.Id); 
           
            DFEventTriggerMethods.sendEmailToMembers(dfeventIds); 
            Double d1 = 90.0;
            Double d2 = 60.0;
            Double d3 = 70.0;
            Double d4 = 50.0;
            
            DFEventTriggerMethods.calculateDistance(d1,d2,d3,d4);
        }
        catch(Exception e){}     
      
    } 
    
    @isTest static void testDFEventTriggerMethods2() {
        try{
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseDFeventGenerator());        
           
            Saved_Search__c ssavedsearch= new Saved_Search__c();
            ssavedsearch.Post_Code__c = '560033';
            ssavedsearch.Email__c = 'test@gmail.com';
            ssavedsearch.Sent_Mail__c= false;
            ssavedsearch.Geolocation__Latitude__s = 30;
            ssavedsearch.Geolocation__Longitude__s = 30;
            insert ssavedsearch;
            
            DF_Contact__c contact = new DF_Contact__c();
            contact.First_Name__c = 'simon';
            contact.Last_Name__c= 'molloy';
            contact.Name = 'simonm';
            insert contact;
            
            DF_Event__c dfevent= new DF_Event__c();
            dfevent.Postcode__c = '560033';
            dfevent.Location_Geographic_Details__Latitude__s = 30;
            dfevent.Location_Geographic_Details__Longitude__s = 30;
            dfevent.Session_Organiser__c = contact.id;
            insert dfevent;
            
            DF_Event__c dfevent1 = new DF_Event__c();
            dfevent1.Postcode__c = '516001';
            dfevent1.Session_Organiser__c = contact.id;
            insert dfevent1;
            
            
            Set<Id> dfeventIds = new Set<Id>();
            dfeventIds.add(dfevent.Id);            
            dfeventIds.add(dfevent1.Id); 
           
            DFEventTriggerMethods.sendEmailToMembers(dfeventIds); 
            Double d1 = 90.0;
            Double d2 = 60.0;
            Double d3 = 70.0;
            Double d4 = 50.0;
            
            DFEventTriggerMethods.calculateDistance(d1,d2,d3,d4);
        }
        catch(Exception e){}     
      
    } 
    
    private static void setUpSystemData(){
		RecordType dfcFriend = [select r.Id from RecordType r where r.DeveloperName = :FRIEND_RT_NAME and r.SobjectType = 'DF_Contact__c' and IsActive = true LIMIT 1];
		RecordType cFriend = [select r.Id from RecordType r where r.DeveloperName = :FRIEND_RT_NAME and r.SobjectType = 'Contact' and IsActive = true LIMIT 1];
		RecordType dfcChampion = [select r.Id from RecordType r where r.DeveloperName = :CHAMPION_RT_NAME and r.SobjectType = 'DF_Contact__c' and IsActive = true LIMIT 1];
		RecordType cChampion = [select r.Id from RecordType r where r.DeveloperName = :CHAMPION_RT_NAME and r.SobjectType = 'Contact' and IsActive = true LIMIT 1];
		
		adminUser = [Select Id From User Where Profile.Name='System Administrator' And IsActive=true limit 1];
		guestUser = [Select Id From User Where UserType='Guest' limit 1];
		portalUser = [Select Id, ContactId from User where Profile.Name='DF HVCP' and IsActive = true LIMIT 1];
		contactRecord = [Select FirstName, LastName, Email from Contact where Id = :portalUser.ContactId LIMIT 1];
		soContactRecord = [Select FirstName, LastName, Email from Contact where RecordTypeId = :cChampion.Id LIMIT 1];
		
    	Global_Setting__c setting = Global_Setting__c.getInstance('webAccountOwnerId');
    	if (setting == null){
    		setting = new Global_Setting__c(Name='webAccountOwnerId',Value__c=adminUser.Id);
        	insert setting;
    	}
    	List<DF_Contact__c> dfConList = new List<DF_Contact__c>();
    	dfConList = [select d.First_Name__c, d.Last_Name__c, d.Email__c, d.RecordTypeId, d.Portal_Contact__c from DF_Contact__c d where d.Portal_Contact__c = :contactRecord.Id LIMIT 1];
    	if (dfConList.size() == 0){
	    	dfContactRecord = new DF_Contact__c();
	    	dfContactRecord.RecordTypeId = [select r.Id from RecordType r where r.DeveloperName = :FRIEND_RT_NAME and r.SObjectType = 'DF_Contact__c' LIMIT 1].Id;
	    	dfContactRecord.Portal_Contact__c = portalUser.ContactId;
	    	dfContactRecord.First_Name__c = contactRecord.FirstName;
	    	dfContactRecord.Last_Name__c = contactRecord.LastName;
	    	dfContactRecord.Email__c = contactRecord.Email;
	    	if (dfContactRecord.Email__c == null) dfContactRecord.Email__c = 'test.email@myemail.com';
	    	insert dfContactRecord;
    	}else {
    		dfContactRecord = dfConList[0];
    	}
    	
    	List<DF_Contact__c> soDFConList = new List<DF_Contact__c>();
    	soDFConList = [select d.First_Name__c, d.Last_Name__c, d.Email__c, d.RecordTypeId, d.Portal_Contact__c from DF_Contact__c d where d.Portal_Contact__c = :soContactRecord.Id LIMIT 1];
    	if (soDFConList.size() == 0){
    		sessionOrganiser = new DF_Contact__c();
	    	sessionOrganiser.RecordTypeId = [select r.Id from RecordType r where r.DeveloperName = :FRIEND_RT_NAME and r.SObjectType = 'DF_Contact__c' LIMIT 1].Id;
	    	sessionOrganiser.Portal_Contact__c = soContactRecord.Id;
	    	sessionOrganiser.First_Name__c = soContactRecord.FirstName;
	    	sessionOrganiser.Last_Name__c = soContactRecord.LastName;
	    	sessionOrganiser.Email__c = soContactRecord.Email;
	    	insert sessionOrganiser;
    	}else {
    		sessionOrganiser = soDFConList[0];
    	}
    	
    	testSession = new DF_Event__c();
    	testSession.RecordTypeId = [select r.Id from RecordType r where r.DeveloperName = :SESSION_RT_NAME and r.IsActive = true and r.SObjectType = 'DF_Event__c' LIMIT 1].Id;
    	testSession.Name = 'Test Session';
    	testSession.Event_Date_Time__c = DateTime.now().addDays(7);
    	testSession.Event_Status__c = 'Available';
    	testSession.Number_of_Places__c = 10;
    	testSession.Session_Organiser__c = sessionOrganiser.Id;
    	insert testSession;
    	
    	testTraining = new DF_Event__c();
    	testTraining.RecordTypeId = [select r.Id from RecordType r where r.DeveloperName = :TRAINING_RT_NAME and r.IsActive = true and r.SObjectType = 'DF_Event__c' LIMIT 1].Id;
    	testTraining.Name = 'Test Training';
    	testTraining.Event_Date_Time__c = DateTime.now().addDays(7);
    	testTraining.Event_Status__c = 'Available';
    	testTraining.Number_of_Places__c = 10;
    	testTraining.Session_Organiser__c = sessionOrganiser.Id;
    	insert testTraining;
    	
    	dfe1 = new DF_EventAttendee__c();
		dfe1.DF_Contact__c = dfContactRecord.Id;
		dfe1.DF_Event__c = testSession.Id;
		system.debug('*** -- Test Code Debug 2 - ' + dfe1.DF_Contact__r.Portal_Contact__c + ' -- ***');
		//This should fire the first trigger
		insert dfe1;
    	
	}
	
	@IsTest(SeeAllData=true)
    static void testSessionTrigger() {
		setupSystemData();
		
		//Update the session and save it - this should fire the 'update' email 
		testSession.Event_Description__c = 'This is an update';
		update testSession;
		
		//Now we cancel the session, and this should fire the 'cancellation' email
		testSession.Event_Status__c = STATUS_CANCELLED;
		update testSession; 
		    	
    }
}