src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <label>Number of Attendees</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Number of Places</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEBChampionManageMySessions.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX controller class for VF Page WEBChampionManageMySessions.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex Class controller for the WEBChampionManageMySessions page.
 *               
 *  Modification History
 *  Date            Who         Description 
 *             
*******************************************************************************************/
public with sharing class WEBChampionManageMySessions extends WEBController {
	public final String STATUS_AVAILABLE = 'Available';
	public final String STATUS_CANCELLED = 'Cancelled';
	public final String STATUS_FULL = 'Full';


	public List<DF_Event__c> upcomingEvents {
		get {
			if (upcomingEvents == null)
				upcomingEvents = new List<DF_EVENT__c>();
			
			return upcomingEvents;
		}
		set;
	}

	public List<DF_Event__c> pastEvents {
		get {
			if (pastEvents == null)
				pastEvents = new List<DF_EVENT__c>();
			
			return pastEvents;
		}
		set;
	}

	public List<DF_Event__c> eventsRequiringFeedback {
		get {
			if (eventsRequiringFeedback == null)
				eventsRequiringFeedback = new List<DF_EVENT__c>();
			
			return eventsRequiringFeedback;
		}
		set;
	}

	public Integer noUpcomingEvents {get;set;}
	public Integer noPastEvents {get;set;}
	public Integer noEventsRequiringFeedback {get;set;}

	public Boolean isChampion {get;set;}
	public Boolean isConverted {get; set;}

	public String messageArea {get;set;}
	public String messageAreaClass {get;set;}

	public Page_Snippet__c totalFriendsSnippet {
		get {
			if (totalFriendsSnippet == null){
				totalFriendsSnippet = [select p.Body_Text__c, p.Unique_Name__c from Page_Snippet__c p where p.Unique_Name__c = 'DementiaFriendsTotalSnippet' LIMIT 1];
			}
			return totalFriendsSnippet;
		}
		set ;
	}
	
	//Constructor
	public WEBChampionManageMySessions() {

		List<DF_Contact__c> contacts = [SELECT Id FROM DF_Contact__c WHERE Portal_Contact__r.Id = :WEBController.thisUser.ContactId LIMIT 1];
		
		DF_Contact__c contact = null;

		System.debug('*** WEBChampionManageMySessions : Checking User');

		isChampion = WEBController.isChampion;
		isConverted = WEBController.isChampionConverted;
		noPastEvents = 0;
		noUpcomingEvents = 0;
		noEventsRequiringFeedback = 0;

		System.debug('*** WEBChampionManageMySessions : User Champion ' + isChampion);

		if (!contacts.isEmpty())
			contact = contacts[0];

		if (contact != null) {
			
			eventsRequiringFeedback = new List<DF_Event__c>();
			upcomingEvents = new List<DF_Event__c>();
			pastEvents = new List<DF_Event__c>();
			for (DF_Event__c dfe : [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c FROM DF_Event__c WHERE Event_Status__c != :STATUS_CANCELLED AND Session_Organiser__c = :contact.Id AND Event_Date_Time__c <= TODAY AND (Number_of_Attendees__c = null OR Number_of_Attendees__c = 0) ORDER BY Event_Date_Time__c DESC]){
				if (dfe.Event_Date_Time__c.getTime() < system.now().getTime()){
					eventsRequiringFeedback.add(dfe);
				}else {
					upcomingEvents.add(dfe);
				}
			}
			for (DF_Event__c dfe : [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c FROM DF_Event__c WHERE Session_Organiser__c = :contact.Id AND Event_Date_Time__c > TODAY and Event_Status__c != :STATUS_CANCELLED ORDER BY Event_Date_Time__c DESC]){
				if (dfe.Event_Date_Time__c.getTime() > system.now().getTime()){
					upcomingEvents.add(dfe);
				}
			}
			//eventsRequiringFeedback = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c FROM DF_Event__c WHERE Event_Status__c != 'Cancelled' AND Session_Organiser__c = :contact.Id AND Event_Date_Time__c < TODAY AND (Number_of_Attendees__c = null OR Number_of_Attendees__c = 0) ORDER BY Event_Date_Time__c DESC];
			//upcomingEvents = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c FROM DF_Event__c WHERE Session_Organiser__c = :contact.Id AND Event_Date_Time__c >= TODAY and Event_Status__c != :STATUS_CANCELLED ORDER BY Event_Date_Time__c DESC];
			for (DF_Event__c dfe : [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c FROM DF_Event__c WHERE Session_Organiser__c = :contact.Id AND Event_Date_Time__c <= TODAY AND Number_of_Attendees__c > 0 ORDER BY Event_Date_Time__c DESC]){
				if (dfe.Event_Date_Time__c.getTime() < system.now().getTime()){
					pastEvents.add(dfe);
				}
			}
			//pastEvents = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c FROM DF_Event__c WHERE Session_Organiser__c = :contact.Id AND Event_Date_Time__c <= TODAY AND Number_of_Attendees__c > 0 ORDER BY Event_Date_Time__c DESC];
		}

		if (eventsRequiringFeedback != null){
			noEventsRequiringFeedback = eventsRequiringFeedback.size();
		}
		
		if (pastEvents != null){
			noPastEvents = pastEvents.size();
		}
		
		if (upcomingEvents != null) {
			noUpcomingEvents = upcomingEvents.size();
		}
	}
}