src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attended?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Ext_Id__c</fullName>
        <externalId>true</externalId>
        <label>Contact Ext Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contacted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contacted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Partner_Organisation_ID__c</fullName>
        <label>Partner Organisation ID</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>DF Champions</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospective</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hiatus/Resting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Friends_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Number of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>RSO</fullName>
        <active>true</active>
        <description>Regional Support Officer</description>
        <label>RSO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>DFC_Code__c</fullName>
        <label>DFC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Partner External Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RSO_AreaLookup__c.object
<CustomObject>
    <description>Regional Support Officers (RSOs) who run Dementia Friend training with the postcode areas they cover.</description>
    <fields>
        <fullName>DFContactId__c</fullName>
        <inlineHelpText>Name of RSO</inlineHelpText>
        <label>Regional Support Officer</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>RSO Area Lookups</relationshipLabel>
        <relationshipName>RSO_Area_Lookups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode_Supported__c</fullName>
        <inlineHelpText>Enter a list of postcodes this RSO supports.  Enter the one or two letters of the postal area</inlineHelpText>
        <label>Postcodes Supported</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RSO Area Lookup</label>
    <nameField>
        <label>RSO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSO Area Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDementiaFriendsControllersHandlers.cls
@isTest
private class TestDementiaFriendsControllersHandlers {
/*
Mike Tinson 24 Jan 2014

After creating trigger handler classes for DF_Contact, DF_Event and DF_EventAttendee.
Need a test class

*/
static testMethod void TestDementiaFriendsHandlers ()
{
   DF_Contact__c dfcon = new DF_Contact__c(Name='Test dfcontact'
                                           ,First_Name__c='Test'
                                           ,Last_Name__c='dfcontact'
                                           ,Status__c='Prospective'
                                           ,email__c= 'email'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alztest.com'
                                           ,RecordTypeId=[Select Id from RecordType where SObjectType='DF_Contact__c' and Name Like 'Dementia Friend Champion'].Id
                                           ,Contact_Number__c='12345678'
                                           ,Eligible__c=FALSE
                                           ,Contacted__c=FALSE
                                           ,Attended__c=FALSE,Note__c='Test Notes');
    insert dfcon;
    DF_Event__c dfeve = new DF_Event__c(Name='dfevent test' 
                                           ,RecordTypeId=[Select Id from RecordType where SObjectType='DF_Event__c' and Name Like 'Champion Training Course'].Id
                                           ,Session_Organiser__c=dfcon.Id, Event_Date_Time__c = system.now());
    insert dfeve;
    DF_EventAttendee__c dfeveattnd = new DF_EventAttendee__c(DF_Contact__c=dfcon.Id,DF_Event__c=dfeve.Id);
    insert dfeveattnd;
    Test.startTest();
    ApexPages.currentPage().getParameters().put('id',dfeve.Id);
    DfEventAttendeeController dfevAt = new DfEventAttendeeController(new ApexPages.Standardcontroller(dfeve));  
    dfevAt.getListEventAttendees();
    dfevAt.save();       
    update dfeveattnd;
    update dfeve;
    update dfcon;
    delete dfeveattnd;
    delete dfeve;
    delete dfcon;
    Test.stopTest();
}
static testMethod void TestDementiaFriendsHandlers2 ()
{
   // insert and update multiple rows
   
   DF_Contact__c dfcon = new DF_Contact__c(Name='Test dfcontact',First_Name__c='Test',Last_Name__c='dfcontact',Status__c='Prospective',Email__c='test'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@dfcon.com',
   RecordTypeId=[Select Id from RecordType where SObjectType='DF_Contact__c' and Name Like 'Dementia Friend Champion'].Id,
                                            Contact_Number__c='12345678',Eligible__c=FALSE,Contacted__c=FALSE,
                                            Attended__c=FALSE,Note__c='Test Notes');
   DF_Contact__c dfcon2 = new DF_Contact__c(Name='Test dfcontact2',First_Name__c='Test',Last_Name__c='dfcontact2',Status__c='Prospective',Email__c='test2'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@dfcon.com',
   RecordTypeId=[Select Id from RecordType where SObjectType='DF_Contact__c' and Name Like 'Dementia Friend Champion'].Id,
                                            Contact_Number__c='12345678',Eligible__c=FALSE,Contacted__c=FALSE,
                                            Attended__c=FALSE,Note__c='Test Notes');

    List <DF_Contact__c> lstDFC = New List<DF_Contact__c>();
    lstDFC.add(dfcon);
    lstDFC.add(dfcon2);
    
    test.startTest();
    
    insert lstDFC;
    update lstDFC;
    
    
    DF_Event__c dfeve = new DF_Event__c(Name='dfevent test'
                              ,RecordTypeId=[Select Id from RecordType where SObjectType='DF_Event__c' and Name Like 'Champion Training Course'].Id
                              ,Session_Organiser__c=dfcon.Id, Event_Date_Time__c = system.now());
    DF_Event__c dfeve2 = new DF_Event__c(Name='dfevent test2'
                               , RecordTypeId=[Select Id from RecordType where SObjectType='DF_Event__c' and Name Like 'Champion Training Course'].Id
                               , Session_Organiser__c=dfcon2.Id, Event_Date_Time__c = system.now());


    List<DF_Event__c> lstDFE = new List<DF_Event__c>();
    
    lstDFE.add(dfeve);
    lstDFE.add(dfeve2);
        
    insert lstDFE;
    update lstDFE;
    
    
    
    
    DF_EventAttendee__c dfeveattnd = new DF_EventAttendee__c(DF_Contact__c=dfcon.Id,DF_Event__c=dfeve.Id);
    DF_EventAttendee__c dfeveattnd2 = new DF_EventAttendee__c(DF_Contact__c=dfcon.Id,DF_Event__c=dfeve.Id);
    List<DF_EventAttendee__c> lstDFEA = New List<DF_EventAttendee__c>();
    lstDFEA.add(dfeveattnd);
    lstDFEA.add(dfeveattnd2);
    insert lstDFEA;
    update lstDFEA;

	test.stopTest();

    /*
    now deletes
    */
    //delete lstDFEA;
    //delete lstDFE;
    //delete lstDFC;
    
    
}

/******************************************************************************************
 * Apex Class to test Partner_OrganisationStatistics. 
*******************************************************************************************/

Static testMethod void testPartner_OrganisationStatistics(){
        //record for champion
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'Dementia Friend Champion' AND isActive = TRUE];
        //record for RSO
        RecordType rtRSO = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'RSO' AND isActive = TRUE];

              
        //New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
        Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
        insert pa;              
        //RSO
        DF_Contact__c dfRSO = new DF_Contact__c(Name='Test RSO'
                                                , Postcode__c='ZZ1 2XX'
                                                , recordtypeid=rtRSO.id
                                                ,First_Name__c = 'Test', Last_Name__c ='DFC'
                                                ,email__c= 'email'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alztest.com');
        insert dfRSO;
        //RSO Area Lookup
        RSO_AreaLookup__c dfAreaLookup = new RSO_AreaLookup__c(Name='Test RSO',DFContactId__c=dfRSO.id,Postcode_Supported__c='NW,SE');
        insert dfAreaLookup;        
        //New DF_Contact__c Record to be added to the test Data.
        //Now insert data causing the DF_Contact__c trigger to fire. 
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', pa.id);  
        Partner_OrganisationStatistics Partner_OrganisationCls= new Partner_OrganisationStatistics(new ApexPages.StandardController(pa));
        System.Debug('################## Total_No_of_Friends_Created  = ' + Partner_OrganisationCls.Total_No_of_Friends_Created + ' #######');
        System.Debug('################## Number_of_Champions_Identified   = ' + Partner_OrganisationCls.Number_of_Champions_Identified + ' #######');
        // now rerun with a champion associated with the partner organisation
        DF_Contact__c df = new DF_Contact__c(Name='Test DFC2'
                                            , Partner_Organisation_ID__c = pa.id
                                            , Contact_Ext_Id__c = 12345678
                                            , Postcode__c='ZZ1 2XX'
                                            , recordtypeid=rt.id
                                            , First_Name__c = 'Test'
                                            , Last_Name__c ='DFC2'
                                            , email__c= 'email2'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alztest.com'
                                            , Total_No_of_Friends_Created__c = 99);
        insert df;        
        Partner_OrganisationCls = new Partner_OrganisationStatistics(new ApexPages.StandardController(pa));
        System.Debug('################## Total_No_of_Friends_Created  = ' + Partner_OrganisationCls.Total_No_of_Friends_Created + ' #######');
        System.Debug('################## Number_of_Champions_Identified   = ' + Partner_OrganisationCls.Number_of_Champions_Identified + ' #######');
        System.AssertEquals(Partner_OrganisationCls.Total_No_of_Friends_Created , 99.0);
        System.AssertEquals(Partner_OrganisationCls.Number_of_Champions_Identified, 1.0);
        Test.stopTest(); 
    }
/******************************************************************************************
 * Apex Class to test RSO Statistics. 
*******************************************************************************************/

Static testMethod void testRSOtatistics(){
        //record for champion
        //RecordType rt = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'Dementia Friend Champion' AND isActive = TRUE];
        //record for RSO
        RecordType rtRSO = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'RSO' AND isActive = TRUE];

              
        //New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
        Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
        insert pa;              
        //RSO
        DF_Contact__c dfRSO = new DF_Contact__c(Name='Test RSO'
                                                , Postcode__c='ZZ1 2XX'
                                                , recordtypeid=rtRSO.id
                                                 ,First_Name__c = 'Test', Last_Name__c ='DFC'
                                                 ,email__c= 'email1'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alztest.com');
        insert dfRSO;
        //RSO Area Lookup
        RSO_AreaLookup__c dfAreaLookup = new RSO_AreaLookup__c(Name='Test RSO',DFContactId__c=dfRSO.id,Postcode_Supported__c='ZZ');
        insert dfAreaLookup;        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', dfRSO.id);  
        DFRSOStatistics RSOCls= new DFRSOStatistics(new ApexPages.StandardController(dfRSO));
        System.Debug('################## Total_No_of_Friends_Created   = ' + RSOCls.Total_No_of_Friends_Created  + ' #######');
        System.Debug('################## Total_No_of_Champions_Created= ' + RSOCls.Total_No_of_Champions_Created + ' #######');
        // now run with a champion associated with the partner organisation
        DF_Contact__c df = new DF_Contact__c(Name='Test DFC2'
                                            ,Partner_Organisation_ID__c = pa.id
                                            , Contact_Ext_Id__c = 12345699
                                            , Postcode__c='ZZ1 2XX'
                                            , RecordTypeId=[Select Id from RecordType where SObjectType='DF_Contact__c' and Name Like 'Dementia Friend Champion'].Id
                                            , First_Name__c = 'Test'
                                            , Last_Name__c ='DFC'
                                            , email__c= 'email2'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alztest.com'
                                            , Total_No_of_Friends_Created__c = 99);
        insert df;        
        RSOCls = new DFRSOStatistics(new ApexPages.StandardController(dfRSO));
        System.Debug('################## Total_No_of_Friends_Created  = ' + RSOCls.Total_No_of_Friends_Created + ' #######');
        System.Debug('################## Total_No_of_Champions_Created= ' + RSOCls.Total_No_of_Champions_Created+ ' #######');
        System.AssertEquals(RSOCls.Total_No_of_Friends_Created, 99.0);
        System.AssertEquals(RSOCls.Total_No_of_Champions_Created, 1.0);
        Test.stopTest(); 
    }



}