src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>E_Newsletter_Subscriber</fullName>
        <active>true</active>
        <label>E-Newsletter Subscriber</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEBForgotPassword.cls
public with sharing class WEBForgotPassword {
    public final String EMPTY_FIELD_VALUE_MSG = 'Value is required and can\'t be empty';
    public final String E_NEWSLETTER_RECORDTYPE = 'E_Newsletter_Subscriber';

    public boolean resetSent {get;set;}
    public boolean noUserFound {get; set;}
    public boolean userIsNewsletter {get; set;}

    public String emailAddress {get;set;}
    public String emailAddressError {get;set;}
    public RecordType eNewsletterRT {get; set;}

    public Page_Snippet__c forgotPasswordSnippet {
        get {
            if (forgotPasswordSnippet == null){
                forgotPasswordSnippet = [select p.Body_Text__c, p.Unique_Name__c from Page_Snippet__c p where p.Unique_Name__c = 'forgotpasswordsnippet' LIMIT 1];
            }
            return forgotPasswordSnippet;
        }
        set ;
    }

    public WEBForgotPassword() {
        emailAddress = '';
        emailAddressError = '';
        resetSent = FALSE;
        userIsNewsletter = FALSE;
        noUserFound = FALSE;
        
        eNewsletterRT = [select r.Id from RecordType r where r.DeveloperName = :E_NEWSLETTER_RECORDTYPE and sObjectType = 'DF_Contact__c' and IsActive = TRUE LIMIT 1];
    }
        
    public PageReference forgotPassword() {
        resetSent = FALSE;
        userIsNewsletter = FALSE;
        noUserFound = FALSE;
        
        if (emailAddress.length() == 0) {
            emailAddressError = EMPTY_FIELD_VALUE_MSG;
            return null;
        }
        
        emailAddress = emailAddress.toLowerCase();
        
        List<DF_Contact__c> dfContactList = new List<DF_Contact__c>();
        dfContactList = [select d.Id, d.Email__c, d.RecordTypeId from DF_Contact__c d where d.Email__c = :emailAddress LIMIT 1];
        
        if (dfContactList.size() == 0){
            noUserFound = TRUE;
            return null;
        }else {
            if (dfContactList[0].RecordTypeId == eNewsletterRT.Id){
                userIsNewsletter = TRUE;
                return null;
            }
        }
        
        system.debug('*** -- About to run Site.forgotPassword with ' + emailAddress + ' -- ***');
        boolean success = Site.forgotPassword(emailAddress);
        system.debug('*** -- forgotPassword success is ' + success + ' -- ***');
        if (success)
            resetSent = TRUE;

        return null;
    }
        
}