src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Ext_Id__c</fullName>
        <externalId>true</externalId>
        <label>Contact Ext Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Organisation_ID__c</fullName>
        <label>Partner Organisation ID</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>DF Champions</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Friends_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Number of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>RSO</fullName>
        <active>true</active>
        <description>Regional Support Officer</description>
        <label>RSO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>DFC_Code__c</fullName>
        <label>DFC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Partner External Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RSO_AreaLookup__c.object
<CustomObject>
    <description>Regional Support Officers (RSOs) who run Dementia Friend training with the postcode areas they cover.</description>
    <fields>
        <fullName>DFContactId__c</fullName>
        <inlineHelpText>Name of RSO</inlineHelpText>
        <label>Regional Support Officer</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>RSO Area Lookups</relationshipLabel>
        <relationshipName>RSO_Area_Lookups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode_Supported__c</fullName>
        <inlineHelpText>Enter a list of postcodes this RSO supports.  Enter the one or two letters of the postal area</inlineHelpText>
        <label>Postcodes Supported</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RSO Area Lookup</label>
    <nameField>
        <label>RSO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSO Area Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDF_ContactTriggerHandler.cls
@isTest
public with sharing class TestDF_ContactTriggerHandler{
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Test Class for DF_ContactTriggerHandler Trigger.
 *  Author  : Ian Smith
 *  Date    : 23-01-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:    Apex Class to test DF_ContactTriggerHandler trigger on the DF_Contact__c object. 
 *               
 *  Modification History
 *  Date            Who     Description 
 *  dd-mm-yyyy      ??      ??
 *  12-03-2014      MT      Update for new routines for update stats
 *  11-04-2014      MT      Updated to add First & Last name whicha are now required.  Email has to be unique.  
 *                             
*******************************************************************************************/

    static testMethod void testInsert(){
        //record for champion
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'Dementia Friend Champion' AND isActive = TRUE];
        //record for RSO
        RecordType rtRSO = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'RSO' AND isActive = TRUE];
              
        //RSO
        DF_Contact__c dfRSO = new DF_Contact__c(Name='Test RSO',First_Name__c = 'Test', Last_Name__c ='RSO', Postcode__c='NW1 2XX', recordtypeid=rtRSO.id, Email__c='test.test'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alzheimers.org.uk');
        insert dfRSO;
        
        //RSO Area Lookup
        RSO_AreaLookup__c dfAreaLookup = new RSO_AreaLookup__c(Name='Test RSO',DFContactId__c=dfRSO.id,Postcode_Supported__c='NW,SE');
        insert dfAreaLookup; 
               
        //New DF_Contact__c Record to be added to the test Data.
        DF_Contact__c df = new DF_Contact__c(Name='Test DFC',First_Name__c = 'Test', Last_Name__c ='DFC', 
                                            Contact_Ext_Id__c = 12345678, Postcode__c='NW1 2XX', recordtypeid=rt.id, Email__c='test.testDFC'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alzheimers.org.uk');
        
        //Now insert data causing the DF_Contact__c trigger to fire. 
        Test.startTest();
        insert df;
        Test.stopTest(); 
    }
    
    
    
    static testMethod void testBulkInsert(){
              
        //New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
        Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
        insert pa;              
        
        //New DF_Contact__c Record to be added to the test Data.
        DF_Contact__c[] dfConToCreate = new DF_Contact__c[]{};
        
        //Create 200 new DF_Contact Records for a Bulk test.
        for(Integer i=0; i< 200; i++){
            DF_Contact__c df = new DF_Contact__c(Name = 'Test DF Con',
                First_Name__c = 'Test',
                Last_Name__c ='DFC',
                Email__c= 'email'+datetime.now().format('YYYYMMDDhhmmsshhmm')+i+'@test.com',
                Contact_Ext_Id__c = i,
                Partner_Organisation_ID__c = pa.id
            );
            dfConToCreate.add(df);
        }
        
        //Now insert data causing the DF_Contact__c trigger to fire. 
        Test.startTest();   
        insert dfConToCreate;
        Test.stopTest();    
    }    
    
    
    
    static testMethod void testUpdate(){
       //record for champion
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'Dementia Friend Champion' AND isActive = TRUE];
        //record for RSO
        RecordType rtRSO = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'RSO' AND isActive = TRUE];
                            
        //RSO
        DF_Contact__c dfRSO = new DF_Contact__c(Name='Test RSO',First_Name__c = 'Test', Last_Name__c ='RSO',Postcode__c='NW1 2XX', recordtypeid=rtRSO.id, Email__c='test.test'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alzheimers.org.uk');
        insert dfRSO;
        
        //RSO Area Lookup
        RSO_AreaLookup__c dfAreaLookup = new RSO_AreaLookup__c(Name='Test RSO',DFContactId__c=dfRSO.id,Postcode_Supported__c='NW,SE');
        insert dfAreaLookup;        
        
        // New DF_Contact__c Record to be added to the test Data.
        DF_Contact__c df = new DF_Contact__c(Name='Test DFC', First_Name__c = 'Test', Last_Name__c ='DFC', Contact_Ext_Id__c = 12345678, Postcode__c='NW1 2XX', recordtypeid=rt.id, Email__c='test.testDFC'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alzheimers.org.uk');
         insert df;  
         
        Test.startTest();  // Start Executing the test.

        df.Name = 'TestDFC';
        df.First_Name__c = 'Test FirstName';
        df.Last_Name__c = 'Test LastName';
        df.Postcode__c='NW1 2YY';  
        update df;
                
        Test.stopTest();  // Stops the test execution.
                
        System.assertEquals('Test FirstName Test LastName', [select Name from DF_Contact__c where id =: df.id].Name);
    }
    
    //2014-06-25 : CSL : Test method for testing DFContactTriggerMethods.dedupeDFContacts(inDFContacts)
    static testMethod void testDedupe(){
       //record for champion
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'Dementia Friend Champion' AND isActive = TRUE];
        //record for RSO
        RecordType rtRSO = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'RSO' AND isActive = TRUE];
                            
        //RSO
        DF_Contact__c dfRSO = new DF_Contact__c(Name='Test RSO',First_Name__c = 'Test', Last_Name__c ='RSO',Postcode__c='NW1 2XX', recordtypeid=rtRSO.id, Email__c='test.test'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alzheimers.org.uk');
        insert dfRSO;
        
        //RSO Area Lookup
        RSO_AreaLookup__c dfAreaLookup = new RSO_AreaLookup__c(Name='Test RSO',DFContactId__c=dfRSO.id,Postcode_Supported__c='NW,SE');
        insert dfAreaLookup;        
        
        // New DF_Contact__c Record to be added to the test Data.
        DF_Contact__c df = new DF_Contact__c(Name='Test DFC', First_Name__c = 'Test', Last_Name__c ='DFC', Contact_Ext_Id__c = 12345678, Postcode__c='NW1 2XX', recordtypeid=rt.id, Email__c='test.testDFC@alzheimers.org.uk');
         insert df;  
         
        Test.startTest();  // Start Executing the test.

		List<DF_Contact__c> dfContactList = new List<DF_Contact__c>();
		dfContactList.add(new DF_Contact__c(Name='Test DFC', First_Name__c = 'Test', Last_Name__c ='DFC', Contact_Ext_Id__c = 12345678, Postcode__c='NW1 2XX', recordtypeid=rt.id, Email__c='test.testDFC@alzheimers.org.uk'));
		DFContactTriggerMethods.dedupeDFContacts(dfContactList);		
                
        Test.stopTest();  // Stops the test execution.
        
    }
  
    static testMethod void testChangeOfRTUpdate(){
       //record for champion
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'Dementia Friend Champion' AND isActive = TRUE];
      //record for friend
        RecordType rtDF = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'Dementia Friend' AND isActive = TRUE];
         //record for RSO
        RecordType rtRSO = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'RSO' AND isActive = TRUE];
                           
        //RSO
        DF_Contact__c dfRSO = new DF_Contact__c(Name='Test RSO',First_Name__c = 'Test', Last_Name__c ='RSO', Postcode__c='NW1 2XX', recordtypeid=rtRSO.id, Email__c='test.test'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alzheimers.org.uk');
        insert dfRSO;
        
        //RSO Area Lookup
        RSO_AreaLookup__c dfAreaLookup = new RSO_AreaLookup__c(Name='Test RSO',DFContactId__c=dfRSO.id,Postcode_Supported__c='NW,SE');
        insert dfAreaLookup;        
        
        // New DF_Contact__c Record to be added to the test Data.
        //DF_Contact__c df = new DF_Contact__c(Name='Test DFC Con', Partner_Organisation_ID__c = pa.id, Contact_Ext_Id__c = 12345678, Postcode__c='NW1 2XX', recordtypeid=rtDF.id, Email__c='test.test'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alzheimers.org.uk', Total_No_of_Friends_Created__c=1);
        //insert df;  

        //New Batch of DF_Contact__c Records to be added to the test Data.
        DF_Contact__c[] lstDFContact = new DF_Contact__c[]{};

        //Create THREE new DF_Contact Records for a Bulk test.
        for (Integer i=0 ; i <3; i++) {
            DF_Contact__c df = new DF_Contact__c(
                Name = 'Test DF Con',
                First_Name__c = 'Test',
                Last_Name__c ='DF Con',
                Email__c= 'emailadfkajfdkj'+datetime.now().format('YYYYMMDDhhmmsshhmm')+i+'@test.com',
                Contact_Ext_Id__c = i
            );  
            lstDFContact.add(df);
        }
        insert lstDFContact;
        
        Test.startTest();  // Start Executing the test.
        List<DF_Contact__c> lstToUpdate = [select Id, Name from DF_Contact__c where Name = 'Test DF Con'];

        for(DF_Contact__c df : lstToUpdate){
            df.Name = 'TestDFC';
            df.First_Name__c = 'Test FirstName';
            df.Last_Name__c = 'Test LastName';
            df.Postcode__c='NW1 2YY';  
            df.recordtypeid=rt.id;                //change of record type to Champion
        }
        update lstToUpdate;

        for(DF_Contact__c df : lstToUpdate){
            df.recordtypeid=rtDF.id;
        }
        update lstToUpdate;

        //df.Partner_Organisation_ID__c =pa2.id;
        for(DF_Contact__c df : lstToUpdate){
            df.recordtypeid=rt.id;                //change of record type to Champion
        }
        update lstToUpdate;
              
        Test.stopTest();  // Stops the test execution.

    }
   
  
    static testMethod void testBulkUpdate(){
        
        //New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
        Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
        insert pa;              
        
        //New Batch of DF_Contact__c Records to be added to the test Data.
        List<DF_Contact__c> lstDFContact = new List<DF_Contact__c>();

        //Create 200 new DF_Contact Records for a Bulk test.
        for (Integer i=0 ; i <200; i++) {
            DF_Contact__c df = new DF_Contact__c(
                Name = 'Test DF Con',
                First_Name__c = 'Test',
                Last_Name__c ='DFC',
                Email__c= 'emailadfkajfdkj'+datetime.now().format('YYYYMMDDhhmmsshhmm')+i+'@test.com',
                Contact_Ext_Id__c = i,
                Partner_Organisation_ID__c = pa.id
            );  
            lstDFContact.add(df);
        }

        List<DF_Contact__c> lstToUpdate = [select Id, Name from DF_Contact__c where Name = 'Test DF Con'];
        for(DF_Contact__c df : lstToUpdate){
            df.Name = 'TestDFcon';
        }
     
        Test.startTest();  // Start Executing the test.  
        update lstToUpdate;
        Test.stopTest();  // Stops the test execution.
    }
    
    
    
    static testMethod void testDelete(){

        //New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
        Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
        insert pa;              
        
        //New DF_Contact__c Record to be added to the test Data.
        DF_Contact__c df = new DF_Contact__c(Name='Test DFC', 
                                            First_Name__c = 'Test', Last_Name__c ='DFC', 
                                            Email__c= 'emailadfkajfdkjDFC'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@test.com',
                                            Partner_Organisation_ID__c = pa.id, Contact_Ext_Id__c = 12345678,Total_No_of_Friends_Created__c=10);
        insert df;
        
        Test.startTest();  // Start Executing the test.            
        delete df;
        Test.stopTest();  // Stops the test execution.
  }    
    
 
 
}