src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attended?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EventAttendeeStatus__c</fullName>
        <label>Event Attendee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Attendee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DFContactAttendeeFlagPhase1.cls
/*
*
* 2014-08-01 : CSL : This is the FIRST of two batch classes that will be run
* to update the DF_EventAttendee__c Status flags on records that are linked to 
* DF Contacts.  This code was originally taken from an Execute Anonymous script
* provided by The Alzheimers Society I.T Department.
*
* To call this class use the following:
//COPY FROM HERE
//RecordType rt = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'Dementia Friend Champion' AND isActive = TRUE];
//String query = 'SELECT DF_Contact__r.Id,DF_Contact__r.Name,COUNT(DF_Contact__c) NumOfAttendees FROM DF_EventAttendee__c WHERE DF_Contact__r.Attended__c = True AND DF_Contact__r.RecordTypeId = \'' + rt.Id + '\' GROUP BY DF_Contact__r.Id,DF_Contact__r.Name HAVING COUNT(DF_Contact__c) = 1 ORDER BY DF_Contact__r.Name ASC';

RecordType rt = [SELECT Id, Name FROM RecordType WHERE sObjectType =: 'DF_Contact__c' AND Name =: 'Dementia Friend Champion' AND isActive = TRUE];
String query = 'SELECT d.Name, d.Id, d.Attended__c, d.Note__c, (Select Id, Event_Status__c, EventAttendeeStatus__c, DF_Event__r.Name From DF_EventAttendees__r) From DF_Contact__c d where d.Attended__c = true and d.RecordTypeId = \'' + rt.Id + '\'';


DFContactAttendeeFlagPhase1 dfcafp1 = new DFContactAttendeeFlagPhase1();
dfcafp1.query = query;

Database.executeBatch(dfcafp1);
//END COPY HERE
*
*/
global class DFContactAttendeeFlagPhase1 implements Database.Batchable<SObject> {
	
	global String query {get; set;}
	
	global Database.QueryLocator start(Database.BatchableContext BC){
    	return Database.getQueryLocator(query);
   	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope){
   		System.debug('### START ###');
		
		
		List<DF_EventAttendee__c> eventAttendeesToSave = new List<DF_EventAttendee__c>();
		
		for (SObject s : scope){
			DF_Contact__c dfc = (DF_Contact__c) s;
			if (dfc.DF_EventAttendees__r.size() > 0){
				for(DF_EventAttendee__c dfea : dfc.DF_EventAttendees__r){
                	dfea.EventAttendeeStatus__c = 'Attended';
                	eventAttendeesToSave.add(dfea);
            	}
			}	
		}
        
        
        if(eventAttendeesToSave.size() > 0){
            
        	//Create a savepoint.
			Savepoint sp = Database.setSavepoint();
            try{
                update(eventAttendeesToSave);
                System.debug('### ' + eventAttendeesToSave.Size() + ' ' + ' DF_EventAttendee__c records Updated.');
            }catch(DmlException e){
            	Database.rollback(sp);
                System.debug('### An exception occurred: ' + e.getMessage());
            }
        }else{
            System.debug('No DF_EventAttendee__c records to Update!');
        }
		
		System.debug('### END ###');
   	}
   	
	global void finish(Database.BatchableContext BC){
		system.debug('*** -- Finished DFContactAttendeeFlagPhase1 -- ***');
	}

}