src/objects/FAQ__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>FAQ Category</inlineHelpText>
        <label>Category</label>
        <referenceTo>FAQ_Category__c</referenceTo>
        <relationshipLabel>FAQs</relationshipLabel>
        <relationshipName>FAQs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <inlineHelpText>This must be a maximum of 255 characters in length.</inlineHelpText>
        <label>Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <inlineHelpText>The order in which the FAQs are listed. Lower numbers go first.</inlineHelpText>
        <label>Rank</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>FAQ</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>FAQ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FAQs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FAQ_Category__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <inlineHelpText>The order in which the FAQ categories are listed. Lower numbers go first.</inlineHelpText>
        <label>Rank</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>FAQ Category</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>FAQ Category List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FAQ Categorys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEBFAQs.cls
public with sharing class WEBFAQs extends WEBController {
	
	public List<FAQ_Category__c> faqCategories {
        get {
            if (faqCategories == null) {
                faqCategories = new List<FAQ_Category__c>();
            }

            return faqCategories;
        }
        private set;
    }

    public List<FAQ__c> faqs {
        get {
            if (faqs == null) {
                faqs = new List<FAQ__c>();
            }

            return faqs;
        }
        private set;
    }

    public Map<Id,List<FAQ__c>> mapFaqs {
        get {
            if (mapFaqs == null) {
                mapFaqs = new Map<Id,List<FAQ__c>>();
            }

            return mapFaqs;
        }
        private set;
    }

	public WEBFAQs() {

		faqs = [SELECT Answer__c,Category__c,Id,Name,Question__c,Rank__c FROM FAQ__c ORDER BY Category__c, Rank__c];

		Set<Id> usedCats = new Set<Id>();

		for (FAQ__c faq : faqs)
			usedCats.add(faq.Category__c);

		faqCategories = [SELECT Id,Name,Name__c,Rank__c FROM FAQ_Category__c WHERE Id IN :usedCats ORDER BY Rank__c];

		Id currentCatId = null;
		Id newCatId = null;
		List <FAQ__c> newFaqs = new List<FAQ__c>();

		for (FAQ__c faq : faqs) {
			newCatId = faq.Category__c;
			System.debug('*** WEBFAQs - newCatId : ' + newCatId);
			if (currentCatId == null)
				currentCatId = newCatId;

			if (newCatId != currentCatId) {
				mapFaqs.put(currentCatId, newFaqs);
				System.debug('*** WEBFAQs Added ' + newFaqs.size() + ' to ' + currentCatId);
				currentCatId = newCatId;
				newFaqs = new List<FAQ__c>();
			}
			newFaqs.add(faq);
		}
		// Don't forget the add the last one
		System.debug('*** WEBFAQs Added ' + newFaqs.size() + ' to ' + newCatId);
		
		mapFaqs.put(newCatId, newFaqs);
	}
}