src/objects/Global_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

src/objects/WEBError_Record__c.object
<CustomObject>
    <fields>
        <fullName>Error_Count_RollUp__c</fullName>
        <label>Total Errors</label>
        <summaryForeignKey>WEBError_Record_Detail__c.WEBError_Record__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Error_Datetime__c</fullName>
        <label>Last Error Datetime</label>
        <summarizedField>WEBError_Record_Detail__c.CreatedDate</summarizedField>
        <summaryForeignKey>WEBError_Record_Detail__c.WEBError_Record__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Session_ID__c</fullName>
        <externalId>true</externalId>
        <label>Session ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WEBError Record</label>
    <nameField>
        <displayFormat>WE-{DD}{MM}{YYYY}-{0000}</displayFormat>
        <label>WEBError Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WEBError Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WEBError_Record_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Error_Condition__c</fullName>
        <label>Error Condition</label>
        <length>48</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <label>Referrer</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>WEBError_Record__c</fullName>
        <label>WEBError Record</label>
        <referenceTo>WEBError_Record__c</referenceTo>
        <relationshipLabel>WEBError Record Details</relationshipLabel>
        <relationshipName>WEBError_Record_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WEBError Record Detail</label>
    <nameField>
        <displayFormat>WED-{DD}{MM}{YYYY}-{0000}</displayFormat>
        <label>WEBError Record Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WEBError Record Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestWebErrorServices.cls
/**
 * Unit test for WebErrorServices class
 */
@isTest
private class TestWebErrorServices {
	
	// test values
	static String oneSessionId = 'abcde';
	static String twoSessionId = 'diff_sid';
	static String referrer = 'http://google.com/about.html';
	static String unsupportedErrorCode = '_DUMMY_';
	
	static List<WEBError_Record__c> findWebErrorRecords(String sessionId) {
		return [SELECT Error_Count_RollUp__c, Last_Error_Datetime__c, Session_ID__c FROM WEBError_Record__c WHERE Session_ID__c = :sessionId];
	}

    static testMethod void testRecordError() {
    	// work only if custom setting is on
    	String errCode = WebErrorServices.AUTH_REQUIRED_CODE;
        WEBError_Record_Detail__c errDetail = WebErrorServices.recordError(errCode, referrer, oneSessionId);
        System.assert(errDetail == null);
        
        // Turn on error logging
        Global_Setting__c gsLogErrors = new Global_Setting__c(Name = WebErrorServices.CS_GLOBAL_NAME, Value__c = WebErrorServices.CS_GLOBAL_VALUE);
        insert gsLogErrors;
    	
        // create record for session first time
        errDetail = WebErrorServices.recordError(errCode, referrer, oneSessionId);
        System.assert(errDetail != null);
        System.assertEquals(WebErrorServices.errorCodeNames.get(errCode), errDetail.Error_Condition__c);
        System.assertEquals(referrer, errDetail.Referrer__c);
        Id masterErrorId = errDetail.WEBError_Record__c;
        
        // create another error for the same session
        errCode = WebErrorServices.MAINTENANCE_CODE;
        errDetail = WebErrorServices.recordError(errCode, referrer, oneSessionId);
        System.assertEquals(WebErrorServices.errorCodeNames.get(errCode), errDetail.Error_Condition__c);
        System.assertEquals(referrer, errDetail.Referrer__c);
        System.assertEquals(masterErrorId, errDetail.WEBError_Record__c);
        Datetime lastDt = [SELECT CreatedDate FROM WEBError_Record_Detail__c WHERE Id = :errDetail.Id].CreatedDate;
        
        // create unsupported error, empty referrer and different session ID
        errDetail = WebErrorServices.recordError(unsupportedErrorCode, null, twoSessionId);
        System.assertEquals(WebErrorServices.errorCodeNames.get(WebErrorServices.GENERIC_ERROR_CODE), errDetail.Error_Condition__c);
        System.assert(String.isBlank(errDetail.Referrer__c));
        System.assertNotEquals(masterErrorId, errDetail.WEBError_Record__c);
        
        // check summary roll-up fields
        List<WEBError_Record__c> masterErrors = findWebErrorRecords(oneSessionId);
        System.assertEquals(1, masterErrors.size());
        WEBError_Record__c errRecord = masterErrors[0];
        System.assertEquals(lastDt, errRecord.Last_Error_Datetime__c);
        System.assertEquals(2, errRecord.Error_Count_RollUp__c);
    }
    
}