src/objects/News__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>News</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>News Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEBNewsTest.cls
@isTest(seeAllData=false)
public with sharing class WEBNewsTest {
  static testMethod void recentNewsTest() {
    News__c news = new News__c();
    news.Title__c = '*** News Title ***';
    news.Body_Text__c = '*** News Body ***';
    
    insert news;

    WEBNews controller;
    
    Test.startTest();
    controller = new WEBNews();

    system.assertEquals(1, controller.newsStories.size());
    system.assertNotEquals(null, controller.selectedStory);
    
    ApexPages.currentPage().getParameters().put('storyId', news.Id);
    controller = new WEBNews();
    system.assertNotEquals(null, controller.selectedStory);
    
    Test.stoptest();
  }
}