src/objects/Page__c.object
<CustomObject>
    <description>Main article page, parent to any Sections</description>
    <fields>
        <fullName>Active_Menu__c</fullName>
        <label>Active Menu</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bottom_Link_List__c</fullName>
        <description>List of links that will appear at the bottom of the page / article</description>
        <label>Bottom Link List</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Date_Published__c</fullName>
        <label>Date Published</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsPublished__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPublished</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Page__c</fullName>
        <label>Parent Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SEO_Description__c</fullName>
        <label>SEO Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SEO_Keywords__c</fullName>
        <label>SEO Keywords</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Menu__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Menu</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of this page / article</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_text__c</fullName>
        <description>Unique text value for this page / article</description>
        <label>Unique Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_Breadcrumb__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Breadcrumb</label>
        <type>Checkbox</type>
    </fields>
    <label>Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Page_Display_Snippet__c.object
<CustomObject>
    <description>Junction object to associate Page Snippets with Pages.</description>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page_Snippet__c</fullName>
        <label>Page Snippet</label>
        <referenceTo>Page_Snippet__c</referenceTo>
        <relationshipLabel>Page Display Snippets</relationshipLabel>
        <relationshipName>Page_Display_Snippets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Page Display Snippets</relationshipLabel>
        <relationshipName>Page_Display_Snippets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Page Display Snippet</label>
    <nameField>
        <displayFormat>PDS-{0000}</displayFormat>
        <label>Page Display Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Display Snippets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CSS_Class__c</fullName>
        <inlineHelpText>CSS class to use when rendering this snippet</inlineHelpText>
        <label>CSS Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_Title__c</fullName>
        <inlineHelpText>The URL of the blue link at the bottom of the snippet</inlineHelpText>
        <label>Link Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_URL__c</fullName>
        <inlineHelpText>The URL of the blue link at the bottom of the snippet</inlineHelpText>
        <label>Link URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <description>Section object used to hold section content for Pages</description>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Heading__c</fullName>
        <label>Heading</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Intro_Paragraph__c</fullName>
        <label>Intro Paragraph</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Link_Title__c</fullName>
        <inlineHelpText>The title of the blue link at the bottom of the section</inlineHelpText>
        <label>Link Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_URL__c</fullName>
        <inlineHelpText>The URL of the blue link at the bottom of the section</inlineHelpText>
        <label>Link URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WEBArticle.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX controller class for VF Page WEBArticle.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex Class loads Page Content, Snippets and Sections for Website content.
 *               
 *  Modification History
 *  Date            Who         Description 
 *  27-02-2014      SM     Updated SOQL Call to only look at 'Active' page sections                  
*******************************************************************************************/
public with sharing class WEBArticle {
	public static final String PARAM_PageId = 'pageId'; // Salesforce Id
	public static final String PARAM_Page = 'page'; // some-unique-name from Unique field
	public static final String PARAM_PageName = 'pageName'; // P-0000
	public static final String PAGE_Error_Page = 'error-page'; // Error page if no article found

	Public Page__c thisPage {
		get {
			if (thisPage == null) {
				thisPage = new Page__c();
				thisPage.Title__c = 'ERROR : PAGE NOT FOUND';
			}
			return thisPage;
		}
		private set;
	}

	Public List<Section__c> pageSections {
		get {
			if (pageSections == null)
				pageSections = new List<Section__c>();
			return pageSections;
		}
		private set;
	}

	Public List<Page_Display_Snippet__c> pageSnippets {
		get {
			if (pageSnippets == null)
				pageSnippets = new List<Page_Display_Snippet__c>();
			return pageSnippets;
		}
		private set;
	}

	public WEBArticle() {
		String pageId = ApexPages.currentPage().getParameters().get(PARAM_PageId);
		String page = ApexPages.currentPage().getParameters().get(PARAM_Page);
		String pageName = ApexPages.currentPage().getParameters().get(PARAM_PageName);

		if (page == null)
			page = '%';

		if (pageName == null)
			pageName = '%';
		
		List<Page__c> pages = [SELECT Show_Menu__c, Use_Breadcrumb__c, Active_Menu__c, Bottom_Link_List__c,Date_Published__c,Id,IsPublished__c,Name,Parent_Page__c,SEO_Description__c,SEO_Keywords__c,Title__c,Unique_text__c FROM Page__c WHERE Name LIKE :pageName AND Unique_text__c LIKE :page LIMIT 1];

		if ((pages != null) && (!pages.isEmpty())) {
			thisPage = pages[0];
			system.debug('*** -- Active Menu = ' + thisPage.Active_Menu__c + ' -- ***');
			pageSections = [SELECT Body_Text__c,Display_Order__c,Heading__c,Intro_Paragraph__c,IsActive__c,Link_Title__c,Link_URL__c,Name,Page__c FROM Section__c WHERE Page__c = :thisPage.Id and IsActive__c = true ORDER BY Display_Order__c];
			pageSnippets = [SELECT Name,Page_Snippet__r.Name__c, Page_Snippet__r.CSS_Class__c, Page_Snippet__r.Body_Text__c, Display_Order__c, Page_Snippet__r.Link_Title__c, Page_Snippet__r.Link_URL__c FROM Page_Display_Snippet__c WHERE Page__c = :thisPage.Id ORDER BY Display_Order__c];
		} else {
			system.debug('*** -- Into error handling -- ***');
			//Error Handling
			pages = [Select p.Use_Breadcrumb__c, p.Unique_text__c, p.Title__c, p.Name, p.IsPublished__c, p.Id, p.Active_Menu__c, 
					(Select Name, Heading__c, Intro_Paragraph__c, Body_Text__c, Display_Order__c, Link_Title__c, Link_URL__c, IsActive__c, 
					Page__c From Sections__r) From Page__c p where p.Unique_text__c = :PAGE_Error_Page LIMIT 1];
					
			pageSections = pages[0].Sections__r;
		}
	}
	
}