src/objects/Saved_Search__c.object
<CustomObject>
    <fields>
        <fullName>Post_Code__c</fullName>
        <label>Post Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Saved Search</label>
    <nameField>
        <displayFormat>Search-{0000}</displayFormat>
        <label>Saved Searches Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Searches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_LocationCallouts.cls
@isTest
private class Test_LocationCallouts{
     @isTest static void testCallout() {
        try{
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());        
            
            Saved_Search__c ssavedsearch= new Saved_Search__c();
            ssavedsearch.Post_Code__c = '638183';
            insert ssavedsearch;
                 
            LocationCallouts.getLocation(ssavedsearch.Id);   
        }
        catch(Exception e){}     
      
    }
}